spacebar in tags and presets addition
monkeytypegame/monkeytype pull request #2938
Opened 2022-05-04 17:50 UTC by aNOOBisTheGod

Now, user can enter tag or preset name with spacebars and they will be changed to underlines(and also in database, so there shouldn't be any cringe spacebar bugs). I think that will be useful

2022-05-04 18:47 UTC, Miodec commented
Build is failing - please fix

2022-05-04 19:03 UTC, aNOOBisTheGod commented
> Build is failing - please fix

done

2022-05-04 19:13 UTC, Bruception commented on frontend/src/ts/db.ts
> +      tag.display = tag.name.replaceAll("_", " ");
I don’t understand, display vs name?

2022-05-04 19:19 UTC, aNOOBisTheGod commented on frontend/src/ts/db.ts
> +      tag.display = tag.name.replaceAll("_", " ");
display is what user will see on website, name is what will be in the database

2022-05-04 19:23 UTC, Bruception commented on frontend/src/ts/db.ts
> +      tag.display = tag.name.replaceAll("_", " ");
Just store it with underscores

2022-05-05 00:12 UTC, Miodec requested changes

2022-05-05 00:12 UTC, Miodec commented on frontend/src/ts/ape/endpoints/presets.ts
> +      name: presetName.replaceAll(" ", "_"),
No need to replace in Ape if you already replace it in the popup code right after the user inputs it. Please remove.

2022-05-05 00:12 UTC, Miodec commented
Have you done any testing?

2022-05-05 03:25 UTC, aNOOBisTheGod commented
> Have you done any testing?

Yep. It works for me

2022-05-05 10:25 UTC, Miodec commented
Tags not using `display` on the typing page and results page.
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/13181393/166905467-b5769dbc-ea2a-4a9b-9e1a-8203c56c2c33.png">

2022-05-05 13:41 UTC, aNOOBisTheGod commented
Done, guess now displays properly

2022-05-05 13:46 UTC, aNOOBisTheGod commented on frontend/src/ts/ape/endpoints/presets.ts
> +      name: presetName.replaceAll(" ", "_"),
removed

2022-05-06 10:41 UTC, Miodec approved these changes
Thanks

2022-05-06 10:42 UTC, merged