Add CONTRIBUTING_BASIC.md and CONTRIBUTING_ADVANCED.md
monkeytypegame/monkeytype pull request #2946
Opened 2022-05-06 06:27 UTC by Matthew-Kwan

### Description

I've refactored the contribution guide into a basic and advanced version. 

`CONTRIBUTING.md` now has a section to help refer potential contributors to the right guide for the change they're trying to make. Most of the content has moved to the advanced contribution guide, but I've kept the guidelines here (open to suggestions on where these should go).

`CONTRIBUTING_BASIC.md` goes through how to use either the VS Code web editor or the Github Web UI to make commits directly through their browser, and open PRs.

`CONTRIBUTING_ADVANCED.md` is mostly a duplicate of the previous state of `CONTRIBUTING.md`, minus sections that stayed in the original file, and minus sections that are no longer relevant. 

Closes #2629 

https://github.com/monkeytypegame/monkeytype/issues/2629

2022-05-06 09:58 UTC, Miodec commented
![image](https://user-images.githubusercontent.com/13181393/167110136-caf5c936-b992-47c7-903c-2550edd15ec2.png)

"For most cases, select the first option for now" but the screenshot shows second option which creates a pull request. Doesnt make sense if they want to commit multiple times or follow the guide because there is a section on creating a pull request just below that.

2022-05-06 16:38 UTC, Matthew-Kwan commented
Good catch, I'll update the screenshot

2022-05-06 21:04 UTC, sillyangel submitted a review, later dismissed
It better and it Clean up some things

2022-05-06 21:04 UTC, sillyangel commented
i like it

2022-05-07 02:03 UTC, Matthew-Kwan commented
@Miodec updated the screenshot to reflect the recommended radio option and added some text around that section to clarify it a bit further.

2022-05-07 11:33 UTC, Miodec requested changes

2022-05-07 11:33 UTC, Miodec commented on CONTRIBUTING_ADVANCED.md
> +When contributing to Monkeytype, it's good to know our best practices, tips, and tricks. First, Monkeytype is written in ~~JavaScript~~ TypeScript, CSS, and HTML (in order of language usage within th
I think we can move this to contributing.md

2022-05-07 11:33 UTC, Miodec commented on CONTRIBUTING_ADVANCED.md
> +While most contributions don't require that you install dependencies, there are a few tools you will need to be able to run the project (this is useful and almost always necessary for tasks like crea
This is the advanced guide so some of the things here don't exactly apply.

2022-05-07 17:02 UTC, Matthew-Kwan commented
@Miodec moved `Getting Started` to `CONTRIBUTING.md` and adjusted the `Prerequisites` section in the advanced guide to tailor it more to the context.

2022-05-08 07:25 UTC, Miodec commented
Thanks

2022-05-08 07:25 UTC, merged

2022-05-08 07:25 UTC, Matthew-Kwan commented
Thanks for the review