Added the brainfck programming language
monkeytypegame/monkeytype pull request #2963
Opened 2022-05-09 18:01 UTC by fehlercode03

Added the basic operations of the brainf*ck programming language

2022-05-09 18:06 UTC, sillyangel commented
how would it make word with it with the brainf language?

2022-05-09 18:07 UTC, sillyangel commented
but nice 👍🏻

2022-05-09 18:31 UTC, sillyangel requested changes
you need to remove the extra space

2022-05-09 19:21 UTC, fehlercode03 commented on frontend/static/languages/_groups.json
> +
It was there before so I left it there

2022-05-11 12:09 UTC, Miodec commented
Not sure if this will work well since it will always separate these characters with a space

2022-05-12 14:49 UTC, fehlercode03 commented
> Not sure if this will work well since it will always separate these characters with a space

What I thought about, maybe small code snippets or something like that e.g.: <<<++.

2022-05-12 18:25 UTC, Miodec commented
> What I thought about, maybe small code snippets or something like that e.g.: <<<++.

That would work - couple hundred snippets of varying length.

2022-05-15 11:10 UTC, Miodec approved these changes

2022-05-15 11:10 UTC, merged