Pr for adding Pop!_Os inspired theme
monkeytypegame/monkeytype pull request #3036
Opened 2022-05-28 05:19 UTC by arthurhawron

### Description

Closes # I tried to make a theme inspired by system76's linux distro pop os. It can be found here: [https://pop.system76.org](url).
Here are some screenshots of the theme: ![test_end](https://i.imgur.com/yLENMik.png) ![in_test](https://i.imgur.com/eySmJW3.png)

2022-05-28 05:38 UTC, rizwanmustafa approved these changes
As far as the code goes, all is well

2022-05-28 05:39 UTC, rizwanmustafa requested changes
The theme color needs some changes

2022-05-28 05:39 UTC, rizwanmustafa commented on frontend/static/themes/pop.css
> +    --colorful-error-extra-color: #ffffff;
Have a different color than `--colorful-error-color`

2022-05-28 05:43 UTC, arthurhawron reviewed
Changed --colorful-error-color to a light blue

2022-05-28 05:58 UTC, rizwanmustafa commented
> Changed

Great. Now the final theme approval will be done by Miodec (Project Owner).

2022-05-29 13:26 UTC, Miodec commented
It looks like a desaturated version of carbon - bit too similar, there are already too many themes on the website. Sorry.

2022-05-29 13:26 UTC, closed without merging