Add additional english quotes
monkeytypegame/monkeytype pull request #3119
Opened 2022-06-13 09:36 UTC by pie-shifted

### Description

Closes #

2022-06-13 14:50 UTC, Bruception commented on frontend/static/quotes/english.json
> +      "text": "It is difficult for me to imagine what \"personal liberty\" is enjoyed by an unemployed hungry person. True freedom can only be where there is no exploitation and oppression of one per
I'm not sure if a quote from Stalin is acceptable. @Miodec

2022-06-13 14:51 UTC, Bruception commented on frontend/static/quotes/english.json
> +      "text": "It is difficult for me to imagine what \"personal liberty\" is enjoyed by an unemployed hungry person. True freedom can only be where there is no exploitation and oppression of one per
I'm not sure if a quote from Stalin is acceptable. @Miodec

2022-06-13 15:37 UTC, Miodec requested changes

2022-06-13 15:37 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "It is difficult for me to imagine what \"personal liberty\" is enjoyed by an unemployed hungry person. True freedom can only be where there is no exploitation and oppression of one per
Remove please

2022-06-13 20:57 UTC, pie-shifted commented
fixed now -_-

2022-06-14 04:03 UTC, Bruception commented
Not sure if we want this in our commit history:

<img width="315" alt="Screen Shot 2022-06-14 at 12 03 52 AM" src="https://user-images.githubusercontent.com/58147810/173490947-4465d42b-39fa-4958-ac58-e59bdfc21905.png">


Please re-open the PR or change the commit message.

2022-06-14 04:55 UTC, closed without merging