Safe leaderboard avatar loading
monkeytypegame/monkeytype pull request #3175
Opened 2022-06-20 18:26 UTC by zachstence

### Description

As requested by @Miodec here
https://github.com/monkeytypegame/monkeytype/pull/3162#issuecomment-1160331780

- Refactor the Discord avatar loading logic I wrote in #3162  into `loadDiscordAvatar` util function
- Use `loadDiscordAvatar` in both the account button and leaderboard avatars
- Adjust leaderboard avatar styling

2022-06-20 18:34 UTC, Bruception commented on frontend/src/ts/elements/leaderboards.ts
> -    const avatarSource = (isCurrentUser && snap) || (entryHasAvatar && entry);
This logic determined where to source the avatar data from.

2022-06-20 18:37 UTC, Bruception commented on frontend/src/ts/elements/account-button.ts
> +    loadDiscordAvatar(discordId, discordAvatar)
Use async/await over promises

2022-06-21 10:35 UTC, Miodec requested changes

2022-06-21 10:35 UTC, Miodec commented on frontend/src/ts/utils/load-discord-avatar.ts
> +  });
Since this is meant to be reused - try to use vanilla for performance (it will surely be faster)

2022-06-21 15:45 UTC, Bruception commented
I'll be re-working this PR. Thank you for the inspiration :)

2022-06-21 15:45 UTC, closed without merging