Adds a reset account button to the settings page
monkeytypegame/monkeytype pull request #3206
Opened 2022-06-23 00:09 UTC by YummyOreo

### Description

Adds reset button

Closes #3173

2022-06-23 00:17 UTC, Bruception commented on backend/src/dal/user.ts
> +export async function resetUser(uid: string): Promise<UpdateResult> {
Don't you also have to delete all result data?

2022-06-23 00:18 UTC, YummyOreo commented on backend/src/dal/user.ts
> +export async function resetUser(uid: string): Promise<UpdateResult> {
that is not done there

2022-06-23 00:20 UTC, YummyOreo commented on backend/src/dal/user.ts
> +export async function resetUser(uid: string): Promise<UpdateResult> {
It is done after resetting the stats

2022-06-23 00:32 UTC, YummyOreo commented
ok everything works

2022-06-23 00:51 UTC, Bruception commented on backend/src/dal/user.ts
> +export async function resetUser(uid: string): Promise<UpdateResult> {
I don’t see any code that deletes all result data for the user.

2022-06-23 01:38 UTC, YummyOreo commented on backend/src/dal/user.ts
> +export async function resetUser(uid: string): Promise<UpdateResult> {
should i move it to that place

2022-06-23 10:06 UTC, Miodec requested changes

2022-06-23 10:40 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  );
Ok

2022-06-24 01:29 UTC, Bruception commented on backend/src/api/routes/ape-keys.ts
> +  "/",
I think this will conflict with the existing delete endpoint.

2022-06-24 01:32 UTC, Bruception commented on backend/src/api/controllers/ape-key.ts
> +export async function resetApeKeys(
reset -> deleteAll

2022-06-24 01:32 UTC, Bruception commented on backend/src/api/controllers/ape-key.ts
> +  await ApeKeysDAL.resetApeKeys(uid);
reset -> deleteAll

2022-06-24 01:32 UTC, Bruception commented on backend/src/api/controllers/preset.ts
> +export async function reset(req: MonkeyTypes.Request): Promise<MonkeyResponse> {
reset -> deleteAll

2022-06-24 01:36 UTC, YummyOreo commented on backend/src/api/routes/ape-keys.ts
> +  "/",
ok

2022-06-24 04:53 UTC, Bruception commented on backend/src/api/routes/ape-keys.ts
> +  "/deleteAll",
Sorry for the confusion, let’s remove the deleteAll path and just leave it as /

2022-06-24 04:57 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +      const responses = [await Ape.users.reset()];
If you use the await keyword, this will not do it parallel.

Just one await:

await Promise.all(responses);

2022-06-24 09:22 UTC, YummyOreo commented on backend/src/api/routes/ape-keys.ts
> +  "/deleteAll",
Ok

2022-06-24 13:44 UTC, Bruception commented on backend/__tests__/dal/ape-keys.spec.ts
> +    expect(apeKeyId0).toBe(undefined);
This isn’t really testing what we want. You need to make a query to the DB and verify that their is no ape keys

2022-06-24 13:56 UTC, YummyOreo commented on backend/__tests__/dal/ape-keys.spec.ts
> +    expect(apeKeyId0).toBe(undefined);
Ok it may be a couple if days till I can fix it.

2022-06-24 14:03 UTC, YummyOreo commented on backend/__tests__/dal/ape-keys.spec.ts
> +    expect(apeKeyId0).toBe(undefined);
Would it be undefined if it was deleted tho

2022-06-24 16:01 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +      const failedResponse = (await results).find(
Do we need an extra await here? Wouldn't the promises be resolved?

2022-06-24 16:05 UTC, Bruception commented on backend/__tests__/dal/ape-keys.spec.ts
> +    expect(apeKeyId0).toBe(undefined);
> Would it be undefined if it was deleted tho

I'm not sure (I think the library we are using stores everything in memory). But we should use the database API to verify that they are actually deleted.

2022-06-24 16:08 UTC, Bruception commented on backend/src/dal/user.ts
> +  return await getUsersCollection().updateOne(
Let's not return anything from this function.

Return type should be `Promise<void>`

2022-06-24 16:11 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +      Notifications.add("Reseting account and stats...", 0);
Resting -> Resetting

2022-06-24 16:20 UTC, YummyOreo commented on backend/__tests__/dal/ape-keys.spec.ts
> +    expect(apeKeyId0).toBe(undefined);
So like try and get them? Using getApeKeys?

2022-06-24 16:36 UTC, Bruception requested changes

2022-06-24 16:36 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +      const responses = [Ape.users.reset()];
can this just be:

```ts
const responses = [
    Ape.users.reset(),
    Ape.presets.reset(),
    Ape.apeKeys.reset(),
    Ape.results.deleteAll(),
];
```

2022-06-24 16:38 UTC, YummyOreo commented on frontend/src/ts/popups/simple-popups.ts
> +      const responses = [Ape.users.reset()];
Thanks never would have thought of that

2022-06-25 15:44 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +        Ape.apeKeys.reset(),
Can we change
reset -> deleteAll

2022-06-25 15:57 UTC, YummyOreo commented on frontend/src/ts/popups/simple-popups.ts
> +        Ape.apeKeys.reset(),
Yeah

2022-06-25 16:46 UTC, YummyOreo commented on frontend/src/ts/popups/simple-popups.ts
> +        Ape.apeKeys.reset(),
Should i do it for users because its not deleting all its just deleting some stuff

2022-06-25 17:06 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +        Ape.apeKeys.reset(),
Not for users

2022-06-28 19:51 UTC, Bruception commented on backend/src/api/routes/ape-keys.ts
> +  RateLimit.apeKeysDelete,
Rate limiter middleware should come after authentication.

2022-06-28 19:52 UTC, Bruception commented on backend/src/api/routes/presets.ts
> +  RateLimit.presetsRemove,
All rate limiter middlewares need to come after

2022-06-28 19:53 UTC, Bruception commented on frontend/src/ts/popups/simple-popups.ts
> +          "There was a error Resetting your account. Try retrying.",
"There was an error resetting your account. Please try again."

2022-06-28 19:56 UTC, Bruception commented on backend/__tests__/dal/ape-keys.spec.ts
> +const COLLECTION_NAME = "ape-keys";
You should do something similar for ape keys like we did for users:
https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/dal/user.ts#L14

2022-06-28 19:59 UTC, Bruception commented
You need to merge the latest changes. There was a change to our rate limit flow:
https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/middlewares/rate-limit.ts

2022-06-28 20:08 UTC, Bruception commented on backend/__tests__/dal/ape-keys.spec.ts
> +    const results = [addApeKey(apeKeys[0]), addApeKey(apeKeys[1])];
```ts
const results = apeKeys.map(addApeKey);
```

2022-06-28 20:10 UTC, Bruception commented on backend/src/dal/ape-keys.ts
> +  await db.collection<MonkeyTypes.ApeKey>(COLLECTION_NAME).deleteMany({ uid });
Could you refactor this to use `getApeKeysCollection`

2022-06-28 22:06 UTC, Bruception commented
Code looks good to me. Needs @Miodec’s approval for client side experience.

On a separate note, do we have any other mechanisms to protect compromised accounts from account data deletion?

Right now it seems like there’s only client side checks but a compromised account’s authentication token can still be used in another client. Maybe we can look into a more robust server side validation check. @Miodec do you know of any firebase APIs that we can use for this? Perhaps 2FA with email pass code?

2022-06-28 22:46 UTC, YummyOreo commented
> On a separate note, do we have any other mechanisms to protect compromised accounts from account data deletion?

you could send a email to the user asking for them to verify that its them

2022-06-28 22:50 UTC, YummyOreo commented
> If we do go this route, perhaps we can consolidate all the account reset logic into a single API endpoint.

consolidating the reset to a single API endpoint would be easy. But we would have find a way to just test the ape-key resetting by its self.

2022-06-28 23:43 UTC, YummyOreo commented
also if we did add 2fa for account deletion, why not add a option to add it on logging in with text message or google Authenticator app

2022-06-29 09:59 UTC, Miodec commented
> Code looks good to me. Needs @Miodec’s approval for client side experience.
> 
> On a separate note, do we have any other mechanisms to protect compromised accounts from account data deletion?
> 
> Right now it seems like there’s only client side checks but a compromised account’s authentication token can still be used in another client (therefore bypassing authentication). Maybe we can look into a more robust server side validation check. @Miodec do you know of any firebase APIs that we can use for this? Perhaps 2FA with email pass code?
> 
> If we do go this route, perhaps we can consolidate all the account reset logic into a single API endpoint.

I mean, do we have a account token leak?

2022-06-29 16:04 UTC, YummyOreo commented
> I mean, do we have a account token leak? We reauthenticate before doing the dangerous stuff, maybe there is a way to check how old the token is

I think even if we reauthenticate it would be safe to do 2fa for that because they may get access to just their account and not their email or phone (however we would do it).

2022-06-29 21:04 UTC, Miodec commented
> > I mean, do we have a account token leak? We reauthenticate before doing the dangerous stuff, maybe there is a way to check how old the token is
> 
> 
> 
> I think even if we reauthenticate it would be safe to do 2fa for that because they may get access to just their account and not their email or phone (however we would do it).

The issue is Firebase doesn't have any easy way of doing 2fa

2022-06-29 23:47 UTC, Bruception commented
> What about google Authenticator

No longer needed. We added a small protection check in the backend that requires the issued token to be recent. This should help a bit.

2022-06-29 23:48 UTC, YummyOreo commented
> > What about google Authenticator
> 
> No longer needed. We added a small protection check in the backend that requires the issued token to be recent. This should help a bit.

ok

2022-07-01 10:12 UTC, Miodec requested changes
After looking into this more, i think it would be better to just hit one endpoint `/user/reset` and do all the changes from there

2022-07-01 18:57 UTC, Bruception commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
Given that these collections are separate from each other, I think we can parallelize these requests.

2022-07-01 19:16 UTC, Bruception commented on backend/src/dal/user.ts
> +  await db.collection<MonkeyTypesResult>("results").deleteMany({ uid });
On a separate note, I think it is weird that we delete presets and ape keys. Those are deletable on their own. @Miodec I think we should only delete results and user data.

2022-07-01 19:18 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  await db.collection<MonkeyTypesResult>("results").deleteMany({ uid });
If it is a full account reset, then it would make sense to reset everything expect login stuff.

2022-07-01 19:21 UTC, Bruception commented on backend/src/dal/user.ts
> +        profileDetails: {
profileDetails can just be an empty object.

2022-07-01 19:23 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
isnt it already doing that?

2022-07-01 19:27 UTC, YummyOreo commented on backend/src/dal/user.ts
> +        profileDetails: {
I cant be an empty object

2022-07-01 19:44 UTC, YummyOreo commented on backend/src/dal/user.ts
> +        profileDetails: {
It cant be an empty object

2022-07-01 21:31 UTC, Miodec commented on backend/src/dal/user.ts
> +  await db.collection<MonkeyTypesResult>("results").deleteMany({ uid });
@Bruception its meant to be a full reset

2022-07-01 21:32 UTC, Miodec commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
> isnt it already doing that?

If you have await on each call that means they will be ran one after each other

2022-07-01 23:22 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
ok

2022-07-02 10:28 UTC, Miodec requested changes

2022-07-02 10:28 UTC, Miodec commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
Also, lets move these calls. Instead of DALs calling other DALs, lets have the user controller call all the DAL files.

2022-07-02 13:29 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
> Also, lets move these calls. Instead of DALs calling other DALs, lets have the user controller call all the DAL files.

so do you mean have it call the `getXCollection` or a function that does what it is doing

2022-07-02 13:31 UTC, Bruception commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
A function, ideally mongodb logic does not exist in controller layer.

2022-07-02 14:22 UTC, YummyOreo commented on backend/src/dal/user.ts
> +  await getApeKeysCollection().deleteMany({ uid });
ok

2022-07-03 02:17 UTC, Bruception commented on backend/src/dal/user.ts
> +        profileDetails: {
How come?

2022-07-03 05:07 UTC, YummyOreo commented on backend/src/dal/user.ts
> +        profileDetails: {
It can only be undefined or a specific type of object somewhere in MonkeyTypes.

2022-07-06 10:59 UTC, merged

2022-07-06 10:59 UTC, Miodec commented
Thanks