Added 20 more English quotes
monkeytypegame/monkeytype pull request #3250
Opened 2022-06-27 13:42 UTC by holyhearted

this isn’t actually 36 commits codespaces is just dumb

2022-06-27 16:03 UTC, Ferotiq commented
Hey it looks like you are just doing all of your changes on the `master` branch of your fork, it would be nice if for each PR you did, you made a new branch on your fork, that way your previous changes don't end up cluttering the commit history in your PRs.
Not a huge deal though.

2022-06-27 17:06 UTC, holyhearted commented
> Hey it looks like you are just doing all of your changes on the `master` branch of your fork, it would be nice if for each PR you did, you made a new branch on your fork, that way your previous changes don't end up cluttering the commit history in your PRs.
> Not a huge deal though.

ahhhhhh! thank you very much, i’ll definitely do that in the future

2022-06-27 17:38 UTC, Miodec requested changes
Most of the sources seem weird? They are just a few words from the quote, or the general idea of the quote. No authors, books, anything?

2022-06-27 17:38 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6138
Remove or replace with a longer version

2022-06-27 17:55 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Bruised",
Jack’s Mannequin — Bruised

2022-06-27 17:55 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Myth",
Beach House — Myth

2022-06-27 17:55 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "text": "\"More.\" You want more, you tell me \"more.\" Only time can run me.",
Beach House — Walk In The Park

2022-06-27 17:56 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "PPP",
Beach House — PPP

2022-06-27 17:56 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Movie Screen",
Chelsea Wolfe — Movie Screen

2022-06-27 17:56 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Flatlands",
Chelsea Wolfe — Flatlands

2022-06-27 17:56 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Nowhere Near",
Yo La Tengo — Nowhere Near

2022-06-27 17:57 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Pristine",
Snail Mail — Pristine

2022-06-27 17:57 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Georgia",
Phoebe Bridgers — Georgia

2022-06-27 17:57 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Motion Sickness",
Phoebe Bridgers — Motion Sickness

2022-06-27 17:57 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "ICU",
Phoebe Bridgers — ICU

2022-06-27 17:58 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "Smoke Signals",
Phoebe Bridgers — Smoke Signals

2022-06-27 17:58 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "source": "My Life in Art",
Mojave 3 — My Life in Art

2022-06-29 12:30 UTC, Miodec approved these changes

2022-06-29 12:30 UTC, merged