11 more quotes for English
monkeytypegame/monkeytype pull request #3308
Opened 2022-07-05 19:00 UTC by holyhearted

11 more (longer) quotes to english.json

2022-07-08 22:12 UTC, Miodec commented
Please go through all the quotes and remove any that are not PG13

2022-07-11 11:31 UTC, Miodec requested changes
Please remove any God references. People get really worked up about this and create drama for a dumb reason so I just wanna avoid the topic all together. Also any political quotes too

2022-07-11 14:32 UTC, holyhearted commented
> Please remove any God references. People get really worked up about this and create drama for a dumb reason so I just wanna avoid the topic all together. Also any political quotes too

i believe you’re referencing an older version of this file, all commented lines have been removed and replaced (have they not?)

2022-07-11 14:35 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "text": "Anyone can change the direction of his life, any time at all, if only he has enough motivation: that was the moral of the story. The cat found it easier to believe this than to think a
remove (?)

2022-07-11 14:36 UTC, holyhearted commented on frontend/static/quotes/english.json
> +      "text": "You were screaming at the Evangelicals - they were screaming right back, from what I remember - when you said, \"I will never be your vegetable.\" Because I think when you're gone it's
to remove

2022-07-15 11:27 UTC, Miodec requested changes

2022-07-15 11:27 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "And if I breathe you, will it kill me? Will you have me, or watch me fall? If I fix you, will you hate me? And would you fuck this, and watch us fall?",
Remove quotes with swear words

2022-07-18 10:33 UTC, Miodec approved these changes

2022-07-18 10:33 UTC, merged