fixing wpm and correctedHistory for Korean
monkeytypegame/monkeytype pull request #3474
Opened 2022-08-30 06:25 UTC by neezacoto

### Fixing
- fixed wpm calculation
- fixed korean word compiling counting as an input, this messed with the wpm.
- fixing corrected history

2022-08-31 11:01 UTC, Miodec requested changes

2022-08-31 11:01 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
> -});
Bring this back

2022-08-31 11:01 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
> -import { skipXpBreakdown } from "../elements/account-button";
Bring this back

2022-09-01 09:29 UTC, Miodec requested changes

2022-09-01 09:29 UTC, Miodec commented on frontend/src/ts/controllers/input-controller.ts
>  $("#wordsInput").on("beforeinput", (event) => {
Instead of adding a new event listener you could integrate into the one in `input-controller.ts` line`792` or `817`

2022-09-02 10:16 UTC, Miodec commented on frontend/src/ts/controllers/input-controller.ts
> +  ) {
Why switch to regex? Whats the performance looking like when doing this on every keypress?

2022-09-02 10:27 UTC, Miodec commented
Overall it looks good, all though it touches the wpm calculation in a lot of places. I think it would be a good idea to get some sort of macro program and verify that the wpm before and after this change is unchanged based on the same exact input

2022-09-02 14:12 UTC, neezacoto commented on frontend/src/ts/controllers/input-controller.ts
> +  ) {
I did this because the isHangul function wasn't working. I could try and see why/play around with it. Is there a definitive way to check performance with mk?

2022-09-03 04:28 UTC, neezacoto commented
performance console print was added, [heres the control](https://github.com/monkeytypegame/monkeytype/pull/3496)

2022-09-03 15:31 UTC, neezacoto commented
[this pr verifies that wpm for Latin isn't being altered ](https://github.com/monkeytypegame/monkeytype/pull/3498)

2022-09-05 11:09 UTC, merged