C rework
monkeytypegame/monkeytype pull request #3483
Opened 2022-08-31 16:19 UTC by egorguslyan

- Extended C wordlist
- Added syntax constructions in C, C++, C#, Arduino (I noticed that they doesn't appear when punctuation is off)
- Added C quotes from public domain (https://www.clc-wiki.net/wiki/K%26R2_solutions)

2022-08-31 16:22 UTC, egorguslyan commented on frontend/static/quotes/code_c++.json
> +      "text": "float Q_rsqrt( float number )\\n{\\n\\tlong i;\\n\\tfloat x2, y;\\n\\tconst float threehalfs = 1.5F;\\n\\n\\tx2 = number * 0.5F;\\n\\ty  = number;\\n\\ti  = * ( long * ) &y; // evil fl
_"Do not include content that contains any libelous or otherwise unlawful, abusive or **obscene** text."_
Can we remove comments?

2022-09-01 09:35 UTC, Miodec commented on frontend/static/quotes/code_c++.json
> +      "text": "float Q_rsqrt( float number )\\n{\\n\\tlong i;\\n\\tfloat x2, y;\\n\\tconst float threehalfs = 1.5F;\\n\\n\\tx2 = number * 0.5F;\\n\\ty  = number;\\n\\ti  = * ( long * ) &y; // evil fl
Yeah remove those

2022-09-01 09:36 UTC, Miodec requested changes

2022-09-01 09:36 UTC, Miodec commented on frontend/static/languages/code_arduino.json
> +    "|="
I think these should be added to punctuation mode, not to the word lists themselves

2022-09-01 18:57 UTC, egorguslyan commented on frontend/static/languages/code_arduino.json
> +    "|="
[test-logic.ts - 261](https://github.com/monkeytypegame/monkeytype/blob/a0b896eb404afcbe645c8d70559f2b68fceb6c11/frontend/src/ts/test/test-logic.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L261)

For now punctuation is the same for all code languages.

[test-logic.ts - 776](https://github.com/monkeytypegame/monkeytype/blob/a0b896eb404afcbe645c8d70559f2b68fceb6c11/frontend/src/ts/test/test-logic.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L776)

 As I can see words with punctuation can not appear until enabled, even html tags (but brainfck emergently stops the loop).

[mt.webm](https://user-images.githubusercontent.com/42677093/187986088-418932ba-d601-4043-a085-e15063cbb6c3.webm)

2022-09-02 10:05 UTC, Miodec commented on frontend/static/languages/code_arduino.json
> +    "|="
> For now punctuation is the same for all code languages.

You can just add an if that checks which language is active and add different punctuation accordingly

2022-09-02 15:31 UTC, Miodec requested changes

2022-09-02 15:31 UTC, Miodec commented on frontend/src/ts/test/test-logic.ts
> +        Config.language == "code_arduino"
Please use `Config.language.startsWith("code")` instead

2022-09-04 10:38 UTC, Miodec approved these changes
Thanks

2022-09-04 10:38 UTC, merged