Added 3 italian quotes
monkeytypegame/monkeytype pull request #3492
Opened 2022-09-02 21:00 UTC by AOTREVAI

### Description

Closes #

2022-09-04 10:39 UTC, Miodec requested changes

2022-09-04 10:39 UTC, Miodec commented on frontend/static/quotes/italian.json
> +      "id": 107
I think these two are too short. We usually want to keep quotes above 50 characters

2022-09-05 10:16 UTC, Miodec requested changes
Very weird quote selection. Please read the quote guidelines again

2022-09-05 10:16 UTC, Miodec commented on frontend/static/quotes/italian.json
> +      "id": 106
Contains mature content, please remove

2022-09-05 10:16 UTC, Miodec commented on frontend/static/quotes/italian.json
> +      "id": 107
References suicide?? Remove

2022-09-05 10:16 UTC, Miodec commented on frontend/static/quotes/italian.json
> +      "length": 108,
Another quote that pretty much mentions war. Remove

2022-09-05 19:35 UTC, AOTREVAI reviewed
i removed the inappropriate quotes

2022-09-05 19:35 UTC, AOTREVAI commented on frontend/static/quotes/italian.json
> +      "length": 108,
it mentions war, but still, it's from a masterpiece movie

2022-09-08 12:06 UTC, Miodec approved these changes

2022-09-08 12:06 UTC, merged