Added quotes from Porter Robinson tracks
monkeytypegame/monkeytype pull request #3550
Opened 2022-09-14 06:08 UTC by seyaidev

Added quotes from Porter Robinson's "Everything Goes On" and "Something Comforting" to `english.json`

_From "Everything Goes On"_
`Don't try to make yourself remember, darling. Don't look for me, I'm just a story you've been told. So let's pretend a little longer. 'Cause when we're gone, everything goes on.`

`But if I was gone tomorrow, won't the waves crash on? Is it selfish that I'm happy as we pass the setting sun? Someday I'll be overcast but you won't have to cry. 'Cause we'll do the grieving while I'm by your side.`

_From "Something Comforting"_
`Take what you want, but you're tied by the tooth. Wasn't it meant to relieve you? So suffer the signs that you needed to change. Heed all the ways you'd been thinking.`

2022-09-15 14:29 UTC, rizwanmustafa approved these changes
As far as the syntax goes. Everything seems fine. It's now up to Miodec

2022-09-16 09:52 UTC, Miodec requested changes
Remove duplicate, also please update the sources to mention the author, for example `Porter Robinson - Everything Goes On`

2022-09-16 09:52 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6229
Same quote twice?

2022-09-19 23:21 UTC, seyaidev commented on frontend/static/quotes/english.json
> +      "id": 6229
Whoops, my bad.

2022-09-19 23:22 UTC, seyaidev commented
Duplicate should be removed now.

2022-09-20 12:55 UTC, Miodec approved these changes

2022-09-20 12:55 UTC, merged