Added some cool deep quotes...
monkeytypegame/monkeytype pull request #3676
Opened 2022-10-22 04:55 UTC by CoolerFred

Just some cool deep quotes... Not much to add.

2022-10-22 11:35 UTC, mrbrianevans commented on frontend/static/quotes/english.json
> +      "text": "Fitter, happier, more productive. Comfortable, not drinking too much. Regular exercise at the gym, three times a week. Getting better with your associate employee contemporaries, at ea
Think it should be `enjoy a drink now and then` rather than `enjoy a drink tow and then`. Typo or spelling mistake needs to be fixed.

2022-10-22 23:05 UTC, CoolerFred commented on frontend/static/quotes/english.json
> +      "text": "Fitter, happier, more productive. Comfortable, not drinking too much. Regular exercise at the gym, three times a week. Getting better with your associate employee contemporaries, at ea
Yeah that should be. Thank you

2022-10-24 10:18 UTC, Miodec requested changes

2022-10-24 10:18 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Fitter, happier, more productive. Comfortable, not drinking too much. Regular exercise at the gym, three times a week. Getting better with your associate employee contemporaries, at ea
Missing capitalisation on "careful"

2022-10-24 10:18 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "The cool thing about these guys is that... is that they have really, really long trunks, and that's- that's cool.",
Replace - with ...

2022-10-25 10:37 UTC, Miodec requested changes

2022-10-25 10:37 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "length": 113,
Incorrect length

2022-10-25 12:01 UTC, merged