Fixed #2361
monkeytypegame/monkeytype pull request #3695
Opened 2022-10-29 13:15 UTC by aungKhantPaing

### Description

Closes #2361. Fixed command line input bug on android. 

1. Replaced the `keyup` listener with `input` listener on the command line component.
2. Removed meta key checks that won't be needed with `input` listener.

2022-10-29 13:20 UTC, rizwanmustafa commented on frontend/src/ts/commandline/index.ts
> -  if (
Why did you remove these lines?

2022-10-29 13:26 UTC, rizwanmustafa requested changes

2022-10-29 13:26 UTC, rizwanmustafa commented on frontend/src/ts/commandline/index.ts
> +$("#commandLine input").on("input", () => {
Replace this with:
```suggestion
$("#commandLine input").on("input", (e) => {
```
 and keep the other lines in.

2022-10-29 13:29 UTC, aungKhantPaing commented on frontend/src/ts/commandline/index.ts
> -  if (
Those lines are for filtering meta keys (Alt, Shift) apart from other keys. `keyup` listener captures both types of event. This won't be the case with `input` listener since it only captures the events from non-meta keys.

2022-10-29 13:31 UTC, rizwanmustafa commented on frontend/src/ts/commandline/index.ts
> -  if (
My bad. I guess then we need to listen to both of these events. 'input' for filtering and 'keyup' for listening to these meta events.

2022-10-29 13:35 UTC, rizwanmustafa commented on frontend/src/ts/commandline/index.ts
> -  if (
Like so:
```
$("#commandLine input").on("keyup", (e) => {
  commandLineMouseMode = false;
  $("#commandLineWrapper #commandLine .suggestions .entry").removeClass(
    "activeMouse"
  );
  if (
    e.key === "ArrowUp" ||
    e.key === "ArrowDown" ||
    e.key === "Enter" ||
    e.key === "Tab" ||
    e.code == "AltLeft" ||
    (e.key.length > 1 && e.key !== "Backspace" && e.key !== "Delete")
  ) {
    return;
  }
  updateSuggested();
});

$("#commandLine input").on("input", () => { updateSuggested(); });
```

2022-10-29 13:42 UTC, rizwanmustafa requested changes

2022-10-29 13:42 UTC, rizwanmustafa commented on frontend/src/ts/commandline/index.ts
> +$("#commandLine input").on("input", (e) => {
My bad again. Please remove the `e` that I added as a parameter. Everything else seems fine.

```suggestion
$("#commandLine input").on("input", () => {
```

2022-10-29 13:43 UTC, rizwanmustafa approved these changes

2022-10-30 22:02 UTC, Miodec commented
Well, that was much easier than i thought. Thanks.

2022-10-30 22:02 UTC, merged