Added 6 quotes
monkeytypegame/monkeytype pull request #3826
Opened 2022-12-12 22:21 UTC by NathanGuidry

Just added some quotes that I enjoy to the project. I want to get more involved with monkeytype but am unsure really where to start so this is what I came up with. My monkeytype username is imbabywild. Not sure if I'll get a "contributor" flare or not from this haha.

2022-12-21 08:48 UTC, RaskiTech approved these changes

2023-01-04 13:01 UTC, Miodec requested changes

2023-01-04 13:01 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6746
How about we change to "Moving on is a simple thing. What it leaves behind, is hard."

2023-01-10 19:41 UTC, Miodec commented
Closing due to inactivity

2023-01-10 19:41 UTC, closed without merging