adding the WPM to the daily leaderboard message
monkeytypegame/monkeytype pull request #3838
Opened 2022-12-16 09:39 UTC by hossammenem

### Adding the WPM along with the placement so users have better information to determine there progress better

Closes #

2022-12-17 09:36 UTC, Miodec requested changes

2022-12-17 09:36 UTC, Miodec commented on backend/src/jobs/announce-daily-leaderboards.ts
> +        body: `Congratulations ${entry.name} on placing ${placementString} with ${wpm} wpm in the ${language} ${mode} ${mode2} daily leaderboard!`,
Please round the WPM

2022-12-19 09:36 UTC, hossammenem commented on backend/src/jobs/announce-daily-leaderboards.ts
> +        body: `Congratulations ${entry.name} on placing ${placementString} with ${wpm} wpm in the ${language} ${mode} ${mode2} daily leaderboard!`,
Hey Miodec, I've already made the changes 2 days ago, can you re-review my request?

2023-01-04 13:23 UTC, Miodec approved these changes

2023-01-04 13:23 UTC, merged