Added quotes
monkeytypegame/monkeytype pull request #3856
Opened 2022-12-26 19:47 UTC by dasle52

### Description

I've just added a few quotes from an artist I like.

2022-12-28 08:51 UTC, UnrealApex requested changes
Thank you for your contribution to Monkeytype. I have left a few suggestions on your PR that you might want to look at.

2022-12-28 08:51 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "text": "I was fast asleep, you stood there by the bedside waiting to haunt by day, someday we might meet, I won't shed a tear for the things that you stole. Your roots go far and deep, they st
The Monkeytype quotes are usually either quotes from books or people. I am not sure if lyrics fit under the "quotes". Check with @Miodec.

2022-12-28 08:51 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +}
Please fix your indentation.

2023-01-03 18:00 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "text": "I was fast asleep, you stood there by the bedside waiting to haunt by day, someday we might meet, I won't shed a tear for the things that you stole. Your roots go far and deep, they st
I have seen lyrics be put as quotes a lot in the past.

2023-01-03 18:06 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "text": "I was fast asleep, you stood there by the bedside waiting to haunt by day, someday we might meet, I won't shed a tear for the things that you stole. Your roots go far and deep, they st
Although I've asked and I'm waiting for a response, thank you!

2023-01-03 18:24 UTC, dasle52 commented
I've done that

2023-01-03 22:13 UTC, UnrealApex requested changes

2023-01-03 22:13 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +  "length": 175
Almost there. The body of the code blocks are also indented. Accepting this change(there is a button below the diff) will fix it.
```suggestion
    {
      "text": "I was fast asleep, you stood there by the bedside waiting to haunt by day, someday we might meet, I won't shed a tear for the things that you stole. Your roots go far and deep, they strangle. Frantic breathing needed to stay afloat.",
      "source": "Quiet Commotion",
      "id": 6745,
      "length": 232
    },
    {
      "text": "Finding myself back to earth, I never wanna come back down. I'm fine here just where I am, with a full moon in my arms.",
      "source": "Quiet Commotion",
      "id": 6746,
      "length": 119
    },
    {
      "text": "Snow's falling down to the ground over secrets I have hid, bleach my sweet mind with the rays of a dying purple sun. Breathing sulfur, my lungs weren't built to last too long.",
      "source": "Quiet Commotion",
      "id": 6747,
      "length": 175
```

2023-01-03 22:26 UTC, UnrealApex commented
Word of advice:  for your commit messages, try to make them more descriptive. In version control this is very important because it lets you(and others) know what exactly a commit added or removed from your code. For example in [this](https://github.com/monkeytypegame/monkeytype/pull/3856/commits/cd4d208509778a849b3b3313eb3be83be436d03a) commit you fix your quotes' indentation and the commit message  is `Added quotes`. `Fixed indentation` would have been a more helpful message for this commit(it is possible to change the commit names; search up `git rebase`). Do not worry about this PR, it is fine since you are starting out, but remember this  when you use Git and maybe other version control systems in the future.

2023-01-04 13:39 UTC, Miodec requested changes

2023-01-04 13:39 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "I was fast asleep, you stood there by the bedside waiting to haunt by day, someday we might meet, I won't shed a tear for the things that you stole. Your roots go far and deep, they st
Yeap, please use correct punctuation.  This quote seems like it could use more full stops

2023-01-04 13:39 UTC, Miodec commented on frontend/static/quotes/english.json
> +  "id": 6747,
Please remove, dont really like the content.

2023-01-05 18:41 UTC, dasle52 reviewed
I have made the changes you requested and apologize for taking so long. I am sorry if the changes are still incorrect, as this is my first time doing a pull request.

2023-01-05 21:23 UTC, UnrealApex submitted a review, later dismissed
Almost there! Since these quotes are lyrics, the song names should be included.

2023-01-05 21:23 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
```suggestion
      "source": "A Rushing River Speaks - Quiet Commotion",
```

2023-01-05 21:23 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
```suggestion
      "source": "I Don't Speak, Pt. 1 - Quiet Commotion",
```

2023-01-05 22:12 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
I apologize for being a bother, but I have noticed some artists who have submitted lyrics without song titles. I am willing to accept your suggestion as well. Is it correct that clicking on "Commit Suggestion" will submit the change? I appreciate your assistance.

2023-01-05 22:16 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
Another question, Is it necessary to open another pull request after the change is accepted in order for the alteration to be applied?

2023-01-06 00:07 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
Lyrics should have the song they came from. Do you know the ids of the lyric quotes that are missing their song names?

2023-01-06 00:09 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
Indeed accepting a code suggestion does just that. You do not need to open a new PR, accepting suggested changes automatically applies them to your code.

2023-01-06 00:54 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
> Lyrics should have the song they came from. Do you know the ids of the lyric quotes that are missing their song names?

I do not exactly know the IDs but I've see one with the band "Syd Matters" but I'm not surprised if it was wrong due to the fact that there was a spelling mistake on said lyrics. Another thing; I have done commit suggestion, is that all I need to do? Can you see if I accepted it and if you can and if I have please say so.

2023-01-06 01:26 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
I will see if I can find them. It appears you have not accepted the commit. There should be a button that looks like this:
![commit suggestion button](https://user-images.githubusercontent.com/79121360/210910840-8b31042a-6415-497c-a994-ec4384edd2ca.png)

2023-01-06 01:53 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
![IMG_20230106_045210](https://user-images.githubusercontent.com/121457195/210913699-30b4144e-e1e8-4d9c-8773-3caa7223d6ef.jpg)

I've done this and this is what it says, have I accepted it now?

2023-01-06 01:56 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
Huh, it does not appear like it. Perhaps it is just glitched. I will just make a PR in your fork. Accepting that should be pretty straightforward.

2023-01-07 00:02 UTC, dasle52 commented on frontend/static/quotes/english.json
> +      "source": "Quiet Commotion",
I've done that, thank you!

2023-01-07 00:17 UTC, Miodec approved these changes

2023-01-07 00:17 UTC, Miodec commented
Please resolve conflict.

2023-01-07 20:26 UTC, UnrealApex approved these changes
LGTM!

2023-01-08 12:09 UTC, Miodec approved these changes

2023-01-08 12:09 UTC, merged