Added quotes to monkey type
monkeytypegame/monkeytype pull request #3910
Opened 2023-01-12 08:54 UTC by TheOrdinaryWizard

### Description

Added a Pulp Fiction quote to english.json

2023-01-12 09:35 UTC, rizwanmustafa requested changes

2023-01-12 09:35 UTC, rizwanmustafa commented on frontend/static/quotes/english.json
>      }
Add a comma at the end of this line

2023-01-23 07:03 UTC, lachie-underhill commented on frontend/static/quotes/english.json
> +      "id": 6762,
This id should be incremented to 6763

2023-01-24 09:04 UTC, rizwanmustafa commented
Closing this PR due to inactivity.

2023-01-28 02:12 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4029666377

2023-01-28 02:37 UTC, Bruception commented
@TheOrdinaryWizard , sorry for the spam. Your PR can RIP now

2023-01-28 02:37 UTC, closed without merging