Add Traditional Chinese language
monkeytypegame/monkeytype pull request #4017
Opened 2023-02-21 16:30 UTC by MHNightCat

### Added more than 200 traditional Chinese words

2023-02-21 16:39 UTC, Miodec commented
Have you verified you can type these words correctly? I know the input system had some issues with Chineese

2023-02-21 16:55 UTC, MHNightCat commented
> Have you verified you can type these words correctly? I know the input system had some issues with Chineese

I don't know how to test

2023-02-21 17:04 UTC, Miodec commented
Run the website locally or put the words into custom mode on monkeytype.com

2023-02-21 17:35 UTC, MHNightCat commented
> 在本地運行網站或在 monkeytype.com 上將文字置於自定義模式

I tried testing it on the site and I think it's ok

2023-02-21 17:46 UTC, MHNightCat commented
I think some people have problems with Chinese input because of the input method (there are many Chinese input methods)
But it's fine if I try it myself

2023-02-22 22:18 UTC, Miodec requested changes

2023-02-22 22:18 UTC, Miodec commented on frontend/static/languages/traditional_chinese.json
> +    "name": "traditional_chinese",
Change this and the name of the file to `chinese_traditional`

2023-02-23 03:58 UTC, MHNightCat commented on frontend/static/languages/traditional_chinese.json
> +    "name": "traditional_chinese",
ok done it

2023-02-23 19:12 UTC, Miodec approved these changes

2023-02-23 19:12 UTC, merged

2023-03-18 15:39 UTC, JacoChong commented
MHNightCat I wanted to publicly thank you on discord but I couldn't find you. I have been holding my desire to have the Chinese language on mt, but there wasn't one and I couldn't help build one cuz of my baby level of programming. I instead added a Jyutping version (as in typing out the pronunciation notation of Cantonese) onto the website.

The server is down now and I couldn't try it out after a long inactivity on mt. Though it's probably using Bopomofo (sorry for assuming you are from Taiwan if it isn't), I am really really glad the day of finally having a legit Chinese language on the website actually came, and I can't wait to see other variations of Chinese languages (such as Cantonese) and input methods for them become available.

There are some testing sites on the web for Chinese created by other Taiwanese but those aren't as high-quality as mt, but because of your time devoted to making this work, I believe that the chinese language community on this website will slowly grow.

Once again thank you so so much for marking this big step for the Chinese language (at least for me it really is). I can't wait any longer to try it out even. THANK YOUUUUUU!!!!