added new english quote
monkeytypegame/monkeytype pull request #4125
Opened 2023-03-29 18:50 UTC by miraiHaGakkariShita

### Description

added a new english quote from attack on titan 

Closes #

2023-03-31 06:30 UTC, UnrealApex requested changes

2023-03-31 06:30 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +    }
JSON objects need to end with a comma if it is not the last one.
```suggestion
    },
```

2023-03-31 06:30 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +      "text": "I'm sorry. I'm sorry. I'm sorry. It's all to save Eldia... and the Island. But not only because of that. The reality outside the walls... was nothing like the world I had dreamed of. I
Disappointed is misspelled.
```suggestion
      "text": "I'm sorry. I'm sorry. I'm sorry. It's all to save Eldia... and the Island. But not only because of that. The reality outside the walls... was nothing like the world I had dreamed of. It was nothing like the world I had seen in Armin's book. When I learned that humanity outside the walls survived... I... was so disappointed. I... wished... for everything to be wiped away.",
```

2023-04-02 15:55 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4589541823

2023-04-02 15:58 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4589552427

2023-04-02 17:06 UTC, miraiHaGakkariShita reviewed
Updated based on the suggestions

2023-04-02 17:12 UTC, miraiHaGakkariShita commented
Do I have to apply them manually, when i batch them up and try to commit suggestions, nothing happens, it just stays that I need to reload, then the same thing again

2023-04-02 17:17 UTC, miraiHaGakkariShita commented
It says: "This diff has recently been updated. Please and try again. ". Though when I try to sync fork it says it's up to date

2023-04-02 18:03 UTC, UnrealApex commented
> Do I have to apply them manually

Yes. Note that one of the suggestions I added is not correct, do not include [it](https://github.com/monkeytypegame/monkeytype/pull/4125#discussion_r1154056876).

2023-04-02 18:14 UTC, UnrealApex requested changes

2023-04-02 18:14 UTC, UnrealApex commented on frontend/static/quotes/english.json
> +	{
The indentation of this line needs to be fixed.

2023-04-02 19:20 UTC, UnrealApex approved these changes
LGTM!

One last thing that could be improved is making the message for your last commit([`683fb18`](https://github.com/monkeytypegame/monkeytype/pull/4125/commits/683fb189b20a18946cb28d7964197df18aa44340)) more descriptive. You can do this by amending the last commit with a new commit message and force pushing:
```sh
git commit -am "Fix indentation"
git push --force
```

2023-04-02 19:33 UTC, miraiHaGakkariShita commented
i have no clue as to how the hell do i use the cli, ill try to comment on the last commit

2023-04-02 19:36 UTC, miraiHaGakkariShita reviewed
Changed the formatting to be appropriate, fixed typos, and set the source to be more particular.

2023-04-02 19:39 UTC, UnrealApex commented
It is not too difficult, but also not necessary. It is just a good practice to have descriptive commit messages. See [commit.style](https://commit.style/), a short, but well written guide on commit messages by Tim Pope.

If you do want to change the message, you will need to install [Git](https://git-scm.com/) on your computer. Once you have that done, clone your fork of the repository(`git clone <your fork url>`) and run the two commands I proved.

2023-04-02 19:43 UTC, UnrealApex commented
> i have no clue as to how the hell do i use the cli, ill try to comment on the last commit

Commenting on a commit is not the same as the commit message. Here is what the message looks like in the UI:
![GitHub commit UI](https://user-images.githubusercontent.com/79121360/229375342-1960aa71-e6dc-468b-88f3-e88f6d8f92d0.png)

2023-04-03 10:24 UTC, Miodec requested changes

2023-04-03 10:24 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "I'm sorry. I'm sorry. I'm sorry. It's all to save Eldia... and the Island. But not only because of that. The reality outside the walls... was nothing like the world I had dreamed of. I
Bit too many ellipsis IMO. Please remove some of them.

2023-04-07 16:43 UTC, closed without merging