Update uzbek.json
monkeytypegame/monkeytype pull request #4195
Opened 2023-04-18 19:24 UTC by AlJavhar

I corrected some wrong words and removed unnecessary ones. I will be glad if I see my language corrected on such sites. Thanks a lot!

### Description

Closes #

2023-04-18 19:27 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4736191912

2023-04-18 19:39 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4736283083

2023-04-18 19:47 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4736337594

2023-04-18 20:23 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4736629105

2023-04-19 08:39 UTC, rizwanmustafa commented
@AlJavhar It seems to me that this PR contains the changes you made in #4194. If my assumption is correct, please close the #4194 PR and continue your work on this PR.

2023-04-19 08:43 UTC, rizwanmustafa commented
As far as this PR is concerned, your changes have introduced some duplicate words:

`eshik`, `do’kon`, `bit`, `pul`, `tuxum`, `gul`, `harakat`, `quloq`.

Please remove them, so that the PR checks can be passed.

2023-04-19 08:43 UTC, rizwanmustafa requested changes
As far as this PR is concerned, your changes have introduced some duplicate words:

`eshik`, `do’kon`, `bit`, `pul`, `tuxum`, `gul`, `harakat`, `quloq`.

Please remove them, so that the PR checks can be passed.

2023-04-19 10:10 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4742087629

2023-04-19 10:23 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4742199991

2023-04-20 10:04 UTC, Miodec commented on frontend/static/languages/uzbek.json
> +    "Javhar",
Did you just add your name to the word list?

2023-04-20 10:05 UTC, rizwanmustafa commented on frontend/static/languages/uzbek.json
> +    "Javhar",
![image](https://user-images.githubusercontent.com/69350358/233334001-f520156f-f20a-4e35-b002-622575cdce86.png)

2023-04-20 10:11 UTC, Miodec commented on frontend/static/languages/uzbek.json
> +    "Javhar",
![image](https://user-images.githubusercontent.com/13181393/233335567-da1c4eea-5d66-4a8f-9a70-06f71203a361.png)

Why is it capitalised then

2023-04-20 10:13 UTC, rizwanmustafa commented on frontend/static/languages/uzbek.json
> +    "Javhar",
Idk why. Maybe he capitalized it accidentally because it's his name

2023-04-25 09:55 UTC, AlJavhar commented on frontend/static/languages/uzbek.json
> +    "Javhar",
This is the Uzbek word. And I would like to be displayed in such a global project))

2023-04-25 10:03 UTC, AlJavhar commented
Fixed Uzbek language

2023-04-25 10:13 UTC, AlJavhar reviewed
I removed all duplicates and similar

2023-04-25 19:04 UTC, AlJavhar commented on frontend/static/languages/uzbek.json
> +    "Javhar",
no, pseudonym!

2023-04-26 09:25 UTC, Miodec commented on frontend/static/languages/uzbek.json
> +    "Javhar",
Still, *your* pseudonym

2023-04-26 09:27 UTC, merged