Create korean.json
monkeytypegame/monkeytype pull request #4204
Opened 2023-04-21 09:09 UTC by jtodaone

### Description

Added Korean Quote.

I don't know if monkeytype programmatically cuts quotes to make it shorter when needed, but if that's not the case, it seems like it might be too long - it is a full 2-page text of a short story. I'd appreciate if anyone could tell me if that's the case or not.

2023-04-21 09:11 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4763312359

2023-04-21 09:16 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4763354629

2023-04-21 09:24 UTC, Miodec commented
> I don't know if monkeytype programmatically cuts quotes to make it shorter when needed, but if that's not the case, it seems like it might be too long

Not sure what you mean by programmatically cutting quotes. Length is ok i guess, but it would be nice to start the korean file with a few more quotes (10-20)

2023-04-21 10:06 UTC, Miodec commented
> > Not sure what you mean by programmatically cutting quotes.
> 
> I was wondering if the website automatically cuts the quote to adequate lengths and not always displaying the full quote.

Always displaying whatever is inside the json file.

2023-04-21 17:09 UTC, jtodaone commented
> Always displaying whatever is inside the json file.

Thanks for clarifying. I will add some more quotes with varying lengths.

2023-04-22 12:58 UTC, pratikpjain approved these changes

2023-05-01 08:50 UTC, rizwanmustafa commented on backend/__tests__/dal/user.spec.ts
Why are these changes in this PR. If you want to have them added to the project, please create a separate PR.

2023-05-01 08:51 UTC, rizwanmustafa requested changes
Please remove the changes to the `user.spec.ts` file.

2023-05-02 12:07 UTC, Miodec commented
Also, please add a few more quotes.

2023-05-02 12:09 UTC, jtodaone commented on backend/__tests__/dal/user.spec.ts
I don't know why that happened, but it might be just out of sync from the master branch. I will fix it later when I add more quotes.

2023-05-16 20:34 UTC, closed without merging