Added English Quotes
monkeytypegame/monkeytype pull request #4275
Opened 2023-05-11 05:18 UTC by TheNatBoi

### Description

Adding various English quotes

2023-05-11 05:20 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4944243637

2023-05-11 05:26 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/4944278798

2023-05-17 10:54 UTC, Miodec requested changes

2023-05-17 10:54 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6917
Remove

2023-05-17 10:54 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6918
Remove

2023-05-17 10:54 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6942
Remove

2023-05-17 10:54 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "length": 73,
Remove

2023-05-17 17:56 UTC, TheNatBoi commented on frontend/static/quotes/english.json
> +      "id": 6917
Fixed

2023-05-17 17:56 UTC, TheNatBoi commented on frontend/static/quotes/english.json
> +      "id": 6942
Fixed

2023-05-19 11:35 UTC, Miodec commented
Please resove merge conflicts

2023-05-22 13:15 UTC, Miodec commented
I think something is messed up because the only file changes i see now is just the french quotes file.

2023-05-31 03:53 UTC, TheNatBoi commented
im just gonna close this and open another one bc i have no clue what its doing

2023-05-31 03:53 UTC, closed without merging