Update _list.json - Added graphite keymap layouts
monkeytypegame/monkeytype pull request #4325
Opened 2023-05-27 04:20 UTC by rdavison

### Description

Adds keymaps for the graphite keyboard layout as described [here](https://github.com/rdavison/graphite-layout).

Closes #

2023-05-29 10:11 UTC, Miodec requested changes

2023-05-29 10:11 UTC, Miodec commented on frontend/static/layouts/_list.json
> +    "type": "ansi",
Change `-` to `_`

2023-05-30 13:21 UTC, rdavison commented on frontend/static/layouts/_list.json
> +    "type": "ansi",
Done in https://github.com/monkeytypegame/monkeytype/pull/4325/commits/3a67bcbc6e5ce87b59aba358c1ce856896737f12

2023-05-30 17:20 UTC, merged

2023-05-30 17:20 UTC, Miodec commented
Thanks