Adding Arabic
monkeytypegame/monkeytype pull request #4356
Opened 2023-06-07 06:29 UTC by m7mdtiger

2023-06-07 06:39 UTC, rizwanmustafa requested changes

2023-06-07 06:39 UTC, rizwanmustafa commented on frontend/static/languages/_list.json
Please revert the changes on this file. It is going to make the reviewing difficult.

2023-06-07 06:40 UTC, rizwanmustafa commented on frontend/static/languages/arabic.json
Revert the changes on this file as well.

2023-06-07 06:58 UTC, m7mdtiger commented on frontend/static/languages/_list.json
Thank you for your comment. I've just added "arabic_1k".
The remaining part involves adjusting the formatting of the document by adding a trailing comma at the end and not to the beginning like: 
[ 
  "english"
  ,"english_1k"
  ,"english_5k"
]

Is it still better to revert the changes !?

2023-06-07 07:00 UTC, m7mdtiger commented on frontend/static/languages/arabic.json
The previous file contains vowel marks and we don't write them on typing!

2023-06-07 07:09 UTC, rizwanmustafa commented on frontend/static/languages/_list.json
Yes

2023-06-07 07:09 UTC, rizwanmustafa commented on frontend/static/languages/arabic.json
Please create a separate PR for that. An ideal PR addresses a single issue.

2023-06-07 07:12 UTC, m7mdtiger commented on frontend/static/languages/arabic.json
Alright, thank you.

2023-06-07 07:30 UTC, m7mdtiger commented on frontend/static/languages/_list.json
Thanks. I've reverted the changes.

2023-06-07 11:50 UTC, Miodec commented
Does this list include diacritics? (which then later can be removed by enabling lazy mode)

2023-06-07 14:17 UTC, m7mdtiger commented
> Does this list include diacritics? (which then later can be removed by enabling lazy mode)

Yes, that should so it for the arabic.json list, which I have already reverted. What remains in this PR is the addition of the arabic_1k.json list, which contains no diacritics.

2023-06-07 20:39 UTC, Miodec commented
All lists should contain diacritics so that the users have the option to either keep them or remove them by enabling lazy mode. Please modify the list to include diacritics.

2023-06-08 09:23 UTC, Miodec commented
Still, thats what lazy mode is for. Some people may want to type them. Please add them.

2023-06-08 09:55 UTC, m7mdtiger commented
> Still, thats what lazy mode is for. Some people may want to type them. Please add them.

Than you. But then the default mode for Arabic should be the lazy mode for all users. Additionally, it's important to consider that the usage of diacritics varies based on the grammatical context, which would require additional time to prepare the list. It may be necessary to allocate a certain percentage for each context, but this task might need more time that I don't have right now!

2023-06-22 20:34 UTC, closed without merging