Josiah quotes
monkeytypegame/monkeytype pull request #4369
Opened 2023-06-11 20:59 UTC by plettj

### Description

- Added 30 quotes
- Replaced duplicate quote with non-duplicate quote
- Fixed incorrect quotation marks

2023-06-11 21:02 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5237474502

2023-06-12 11:17 UTC, Miodec commented on frontend/static/quotes/english.json
>      },
Whats up with this

2023-06-12 11:19 UTC, Miodec reviewed
Theres no need to replace all the quotation marks, they are replaced automatically.

2023-06-12 15:48 UTC, plettj commented on frontend/static/quotes/english.json
>      },
Someone submitted the same Theodore Roosevelt quote twice. Instead of deleting it and rewriting all the IDs, I put one of my quotes in its place

2023-06-13 14:40 UTC, plettj commented on frontend/static/quotes/english.json
>      },
Thanks, done

2023-06-14 09:42 UTC, Miodec requested changes
There was a different quote PR opened before yours. Please resolve conflicts.

2023-06-14 09:42 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6943
Might upset some religious people (usually i avoid any references to religion), so please remove this one and any others that could refer to religious topics.

2023-06-14 17:01 UTC, plettj commented on frontend/static/quotes/english.json
> +      "id": 6943
Thanks, removed two

2023-06-14 17:03 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5270006223

2023-06-15 14:05 UTC, merged