split smoothCaret into several modes
monkeytypegame/monkeytype pull request #4374
Opened 2023-06-12 19:47 UTC by Im-0xea

### Description

I hope its appropriate to make this another pr, I didn't want to commit spam as I reverted all of my previous ones.

Switched smoothCaret from a boolean to a enum of "off" / "slow" / "medium" / "fast", as suggested by @Miodec in my previous pr #4368 , with regard to the previously stored boolean value

2023-06-12 20:02 UTC, Miodec commented on backend/src/api/schemas/config-schema.ts
>    quickRestart: joi.string().valid("off", "tab", "esc"),
Add a comment to 'Remove boolean after this change has been deployed for a bit'

2023-06-12 20:07 UTC, Miodec requested changes

2023-06-12 20:07 UTC, Miodec commented on frontend/src/ts/config.ts
> +  mode: "off" | "slow" | "medium" | "fast",
Move this to `types.d.ts` as `SmoothCaretMode`

2023-06-12 20:07 UTC, Miodec commented on frontend/src/ts/config.ts
>    }
Instead of handling this here, add migration code to db.ts which replaces the config value to one of the strings if its a boolean.

2023-06-12 20:46 UTC, Im-0xea commented on frontend/src/ts/config.ts
>    }
oooh yeah, how silly of me :,)

2023-06-12 21:03 UTC, Im-0xea commented
Implemented your requested changes :P

2023-06-14 10:15 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5265829547

2023-06-14 10:50 UTC, Miodec requested changes

2023-06-14 10:50 UTC, Miodec commented on frontend/src/ts/config.ts
> -    $("#caret").css("animation-name", "caretFlashHard");
Look like you lost this animation change. Right now if you disable the smooth caret it still smoothly flashes. Please bring it back.

2023-06-14 10:54 UTC, Im-0xea commented on frontend/src/ts/config.ts
> -    $("#caret").css("animation-name", "caretFlashHard");
oh, sorry what a stupid thing to miss, will fix that right away

2023-06-14 11:59 UTC, merged

2023-06-14 11:59 UTC, Miodec commented
Thanks