Add quotes
monkeytypegame/monkeytype pull request #4403
Opened 2023-06-26 03:13 UTC by Warrobot10

Hey there! ~ I hope I get this right, but I added some quotes!
Thanks!

2023-06-26 11:17 UTC, Miodec requested changes

2023-06-26 11:17 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 6981
Quote is too short. Please use remove or use a longer version (above 60 characters)

2023-06-29 10:53 UTC, Miodec commented
Hmmm, looking at the quotes I'm not sure if i like them actually. One mentiones jumping off a cliff and the other one about giving up. Sorry.

2023-06-29 10:53 UTC, closed without merging

2023-06-30 02:24 UTC, Warrobot10 commented
All good, I guess I thought it’d be a good inspirational quote.