Notify users for school email address (.edu)
monkeytypegame/monkeytype pull request #4404
Opened 2023-06-26 09:28 UTC by aviiciii

### Description
This pull request adds a new feature to the sign-up process that checks if the provided email address is a school email address (.edu domain). It also includes an indicator to notify users to consider using a personal email address for better email functionality.

### Demo

https://github.com/monkeytypegame/monkeytype/assets/88141521/2e2b3ab2-6e26-41fd-8758-8d1e05adca5e

Closes #4393

2023-06-26 13:06 UTC, aviiciii commented
Hey, I added university domain (.ac) and school domains (.sch). 
note that .ac is a tld and a second-level domain whereas .sch is second-level domain only.

2023-06-26 13:50 UTC, Miodec requested changes

2023-06-26 13:50 UTC, Miodec commented on frontend/src/ts/pages/login.ts
> +    (emailIndicator.get() !== "valid" && emailIndicator.get() !== "edu") ||
Remove. I think we should still allow the signup if the user wants to use that email

2023-06-26 14:37 UTC, aviiciii commented on frontend/src/ts/pages/login.ts
> +    (emailIndicator.get() !== "valid" && emailIndicator.get() !== "edu") ||
(emailIndicator.get() !== "valid" && emailIndicator.get() !== "edu") 
this simply says that it must either be "valid" or "edu".

2023-06-27 12:04 UTC, aviiciii commented on frontend/src/ts/pages/login.ts
> +    (emailIndicator.get() !== "valid" && emailIndicator.get() !== "edu") ||
@Miodec ?

2023-06-29 10:48 UTC, merged

2023-06-29 10:48 UTC, Miodec commented
Thanks

2023-06-29 10:49 UTC, Miodec commented on frontend/src/ts/pages/login.ts
> +    (emailIndicator.get() !== "valid" && emailIndicator.get() !== "edu") ||
Yeah youre right