Added configuration for typing speed unit, removed alwaysShowCPM
monkeytypegame/monkeytype pull request #4492
Opened 2023-07-31 14:31 UTC by fehmer

### Description

Remove config `alwaysShowCPM` and replace with `typingSpeedUnit`. Supported units are `wpm`, `cpm`, `wps` and `cps`.

Closes #4491

2023-07-31 14:39 UTC, Miodec requested changes
Also, make sure to add `alwaysShowCPM` to the `replaceLegacyValues` in `config.ts`

2023-07-31 14:39 UTC, Miodec commented on frontend/src/ts/account/pb-tables.ts
> +  const wpmCpm = Config.typingSpeedUnit;
Rename this variable

2023-07-31 14:39 UTC, Miodec commented on frontend/src/ts/account/pb-tables.ts
> +    let wpmString: number | string = Misc.convertTypingSpeed(
Rename to `speedString` or `stringWIthUnit`

2023-07-31 14:39 UTC, Miodec commented on frontend/src/ts/constants/default-config.ts
> +  typingSpeedUnit: "wpm", //TODO: change to wpm
What does this todo mean?

2023-07-31 14:39 UTC, Miodec commented on frontend/src/ts/utils/misc.ts
> +export function translateTypingSpeed(
Maybe rename to something like `getFullSpeedUnitString` ?

2023-07-31 15:24 UTC, fehmer commented on frontend/src/ts/account/pb-tables.ts
> +  const wpmCpm = Config.typingSpeedUnit;
done

2023-07-31 15:24 UTC, fehmer commented on frontend/src/ts/account/pb-tables.ts
> +    let wpmString: number | string = Misc.convertTypingSpeed(
done

2023-07-31 15:25 UTC, fehmer commented on frontend/src/ts/utils/misc.ts
> +export function translateTypingSpeed(
done

2023-07-31 15:25 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5716538325

2023-08-01 15:43 UTC, fehmer commented on frontend/src/ts/pages/account.ts
> +  console.log(labels);
TODO remove

2023-08-03 09:51 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5749204337

2023-08-03 10:57 UTC, Miodec commented
<img width="1434" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/4485fe64-6e20-4051-9e67-b05e1c7ed2ed">

Something is still wrong with the account graph scale, one result is not visible

2023-08-03 11:10 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5749954903

2023-08-03 11:18 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5750029152

2023-08-03 12:29 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5750029152

2023-08-03 13:22 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5751271990

2023-08-04 11:22 UTC, merged