Updated the overlay text of the screenshot button
monkeytypegame/monkeytype pull request #4507
Opened 2023-08-06 09:40 UTC by Mammoets

Updated the overlay text of the screenshot button to be more descriptive.

### Description

When a test is completed, one of the buttons on the page is the screenshot button. The current overlay text for the screenshot button says "Save screenshot", which is not adequately descriptive as the button copies the screenshot to the clipboard rather than saving it. This might have caused confusion or slowed down the user interaction process. The updated text, "Copy Screenshot to Clipboard," more accurately describes the button's functionality, making it clearer and more intuitive for the users.

### Closes 

The updated text, "Copy Screenshot to Clipboard," more accurately describes the button's functionality. There are no issues related to this PR.

2023-08-08 09:48 UTC, Miodec requested changes

2023-08-08 09:48 UTC, Miodec commented on frontend/src/ts/commandline/lists/result-screen.ts
>      alias: "ss picture",
Add `save` as alias

2023-08-08 09:48 UTC, Miodec commented on frontend/static/challenges/sourcecode.txt
> +                    aria-label="Copy screenshot to clipboard"
Revert this change please.

2023-08-08 23:35 UTC, Mammoets commented
Fixed comments

2023-08-08 23:35 UTC, Mammoets commented
fixed comments

2023-08-10 12:49 UTC, merged

2023-08-10 12:49 UTC, Miodec commented
Thanks