Feat: Show min speed if not qualified for daily lb.
monkeytypegame/monkeytype pull request #4519
Opened 2023-08-09 10:55 UTC by HyperDanisH

### Description

This PR tends to close #4424. I have the first prototype of this feature ready. I really need a review if there is something I can improve in this.

Best,

2023-08-09 11:01 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5808158002

2023-08-09 11:10 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5808255043

2023-08-09 11:18 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5808327912

2023-08-09 11:25 UTC, HyperDanisH commented
> Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5808158002

Hi,
I am trying to resolve ci-fe errors but I am unable to. Please help me with this.

2023-08-10 11:37 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5820559845

2023-08-10 11:46 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5820638995

2023-08-10 12:25 UTC, Miodec commented
> Hi,
> I am trying to resolve ci-fe errors but I am unable to. Please help me with this.

Did you read the actual error? You just need to change `let` to `const`

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/edc396e8-b52a-45fb-959e-5f1e92f34db6)

2023-08-10 12:49 UTC, Miodec requested changes

2023-08-10 12:49 UTC, Miodec commented on frontend/src/ts/elements/leaderboards.ts
>    }
Move this to the else statement of the `if (currentRank[lb])` check.

2023-08-10 12:49 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
> +
Please use camel case

2023-08-10 12:49 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
> +    const [[, rank], [, count], [, result], [, least_score]] = await connection
Rename to `minScore`

2023-08-10 12:49 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
> +    const min_rank =
Rename to `minWpm`, add decimal places to it.

2023-08-10 12:49 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
>      return {
Im not really digging this 3 possible return types. I think we can always return one object:
```
{
  minWpm: float,
  count: number,
  rank: number | null,
  entry: DailyLeaderboardEntry
}
```
Also dont forget to remove `rank` and `count` from the entry type.

Then ofcourse modify the frontend to accept the new return type.

2023-08-10 12:49 UTC, Miodec commented on frontend/src/ts/elements/leaderboards.ts
When you edit the return type, these won't be needed.

2023-08-10 21:57 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5826457953

2023-08-12 08:46 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5840402251

2023-08-12 16:41 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +    const min_rank =
This doesn't return WPM, this would return our custom encoded score.
There needs to be an additional processing step to undo the encoding:
https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/utils/misc.ts#L104C9-L104C9

2023-08-12 16:42 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +      .zrange(leaderboardScoresKey, 0, 1, "WITHSCORES")
This would return the first score, not the last.

2023-08-12 16:45 UTC, Bruception commented on frontend/src/ts/elements/leaderboards.ts
> +const minRank: {
Just use record
```suggestion
const minimumQualifyingWpm: Record<LbKey, number> = {
    "15": 0,
    "60": 0,
};
```

2023-08-12 16:47 UTC, Bruception commented on frontend/src/ts/elements/leaderboards.ts
> +        minRank[lb] !== null ?
In what cases would it be null? When no scores are recorded?
I think we should always show a number. I think the lowest WPM that Monkeytype accepts is like 10 or something.

2023-08-12 16:55 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
>    public async getRank(
I'm not sure how I feel about coupling this with `getRank`.
A `DailyLeaderboardEntry` contains stats for a single user. By including minimum qualifying WPM, we kind of change that definition.

- I think I'd prefer if we expose a new API that just gets general leaderboard statistics.
OR
- Update the existing leaderboards API to return additional metadata describing these stats:
```json
{
    "message": "Leaderboard retrieved",
    "data": {
        "metadata": {
            // New statistics here
        },
        "results": [
            {
                "consistency": 89.85,
                "punctuation": false,
                "timestamp": 1686604543792,
                "acc": 95.73,
                "raw": 294.75,
                "wpm": 273.35,
                "lazyMode": false,
                "uid": "yjJwJdoh04hnms9sD0UdpfeoAXV2",
                "name": "rocket",
                "discordId": "262944140273123359",
                "discordAvatar": "bb2b547f7c6ac3d0f114ab87f75b8b98",
                "rank": 1,
                "badgeId": 13
            },
            ...
        ]
    }
}
```

2023-08-12 16:56 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +      least_score.length > 0 ? parseInt(least_score[1].slice(1, 4)) : 0;
nvm here it is.
Challenge: Try doing this with numeric operators only :P

2023-08-12 16:57 UTC, Bruception requested changes
Thank you for taking this on :)

However, I do not agree with this implementation. Please consider the alternatives I mentioned. LMK if you have any questions, happy to help.

2023-08-12 16:58 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
> +    const min_rank =
The `slice(1,4)` means the wpm will get extracted. Then if we slice out the 5th and 6th character (times `0.01`) , it will give us the decimal places.

2023-08-12 17:00 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
>    public async getRank(
The type is already all over the place. We already include the `count`, which is not exactly exclusive to the singular entry. I did suggest a new return type in my other comment though.

2023-08-13 03:32 UTC, HyperDanisH commented on frontend/src/ts/elements/leaderboards.ts
> +        minRank[lb] !== null ?
I will certainly do something of that.

2023-08-13 16:42 UTC, HyperDanisH commented on frontend/src/ts/elements/leaderboards.ts
>    }
Review this change I made in the latest commit. Tell me if I didn't do it right.

2023-08-13 16:44 UTC, Miodec commented on frontend/src/ts/elements/leaderboards.ts
>    }
Yeah thats good

2023-08-13 16:44 UTC, HyperDanisH commented on backend/src/utils/daily-leaderboards.ts
>      return {
Tbh, I am sorry but I am unable to understand this. It could be issue with my english but I am sorry, I would require to elaborate this further more.
How can we sent rank if there is not any?

2023-08-13 16:46 UTC, Miodec commented on backend/src/utils/daily-leaderboards.ts
>      return {
The type is `number | null` - so, if there is no rank, just send `null`.

2023-08-13 16:47 UTC, HyperDanisH commented
> Thank you for taking this on :)
> 
> However, I do not agree with this implementation. Please consider the alternatives I mentioned. LMK if you have any questions, happy to help.

I found out that this could be one way of many others. @Miodec what are your thoughts on this one. Let me now all this, I am willing to take this project on from scratch.
Best,

2023-08-13 16:48 UTC, Miodec commented
> > Thank you for taking this on :)
> > However, I do not agree with this implementation. Please consider the alternatives I mentioned. LMK if you have any questions, happy to help.
> 
> I found out that this could be one way of many others. @Miodec what are your thoughts on this one. Let me now all this, I am willing to take this project on from scratch. Best,

Its ok. Once you take on the suggestions in the comments, it will be good to merge.

2023-08-13 17:18 UTC, Miodec requested changes
You've resolved some of the conversations but didnt actually address the issues. The `zrange` code seems unchanged, the minWpm is still a number without decimal places, and i would be nice to rework the return type as suggested in one of the comments.

2023-08-13 21:04 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +    const min_rank =
This should be done like this:
```ts
const WPM_SHIFT_AMOUNT = 10 ** 10;

function extractWpmFromKogascore(kogascore: number): number {
    return (Math.floor((kogascore / WPM_SHIFT_AMOUNT)) % 10_000) / 100;
}
```

2023-08-13 21:10 UTC, Bruception commented
> You've resolved some of the conversations but didnt actually address the issues. The `zrange` code seems unchanged, the minWpm is still a number without decimal places, and i would be nice to rework the return type as suggested in one of the comments.

Actually, the usage of `zrange` is correct. I forgot that this function orders from lowest to highest by default. Should be all set there.

2023-08-13 21:30 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +      .zrange(leaderboardScoresKey, 0, 1, "WITHSCORES")
Use 0, 0:
```
127.0.0.1:6379> ZRANGE test 0 1 WITHSCORES
1) "bruce"
2) "123"
3) "bro"
4) "1234"
127.0.0.1:6379> ZRANGE test 0 0 WITHSCORES
1) "bruce"
2) "123"
```

2023-08-13 22:00 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +    const min_rank =
Disregard, string operation is fine, but I'd still wrap it into a function under `misc.ts`:
```ts
function extractWpmFromKogascore(kogascore: string): number {
    return parseInt(score.slice(1, 6)) / 100;
}
```

2023-08-16 04:48 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5874741186

2023-08-16 04:53 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5874771427

2023-08-17 07:08 UTC, HyperDanisH commented
Hi @Miodec I was actually wating for it to be merged if I did all right. If there are some questions still, you can say me I can resolve those.

2023-08-17 08:56 UTC, Miodec commented
> Hi @Miodec I was actually wating for it to be merged if I did all right. If there are some questions still, you can say me I can resolve those.

You still have not changed the return type, as suggested in the comments.

2023-08-17 08:57 UTC, HyperDanisH commented
> > Hi @Miodec I was actually wating for it to be merged if I did all right. If there are some questions still, you can say me I can resolve those.
> 
> You still have not changed the return type, as suggested in the comments.

Saw it late, It's my completely fault. Working on it right away!

2023-08-17 09:35 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5889192525

2023-08-17 09:45 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5889297809

2023-08-18 08:46 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5900640494

2023-08-18 08:57 UTC, HyperDanisH commented
Have changed to int returned to float, would appericiate if you have a look at it.

2023-08-18 12:29 UTC, Bruception requested changes

2023-08-18 12:29 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +      .zrange(leaderboardScoresKey, 0, 1, "WITHSCORES")
ZRANGE 0,0 not 0,1

2023-08-18 12:29 UTC, Bruception commented on backend/src/utils/daily-leaderboards.ts
> +interface DailyLeaderboardMinRank {
Don’t add a new interface, just extend the existing one

2023-08-18 12:29 UTC, Bruception commented on frontend/src/ts/elements/leaderboards.ts
> +const minWpm: {
Use typescript Record type

2023-08-20 03:03 UTC, HyperDanisH commented on frontend/src/ts/elements/leaderboards.ts
> +const minWpm: {
Need review on this one

2023-08-20 03:04 UTC, HyperDanisH commented on backend/src/utils/daily-leaderboards.ts
> +interface DailyLeaderboardMinRank {
How should I do that?

2023-08-20 03:06 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5915048568

2023-08-20 18:19 UTC, Ferotiq commented on frontend/src/ts/elements/leaderboards.ts
> +const minWpm: {
```ts
const minWpm: Record<LbKey, number | null> = { ... };
```

2023-08-20 18:38 UTC, Ferotiq commented on backend/src/utils/daily-leaderboards.ts
> +interface DailyLeaderboardMinRank {
@HyperDanisH Simply add `minWpm` to the `DailyLeaderboardEntry` interface, it does not need to be in it's own interface. You can return `DailyLeaderboardEntry | null` from `getRank`. The `rank === null` check would have to be modified, and could potentially be removed in favor of a ternary expression in the final return.

2023-08-21 10:22 UTC, Miodec commented
@HyperDanisH i'll help you out here

2023-08-21 11:44 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5925752002

2023-08-21 12:06 UTC, merged