feat: Input history heatmap is add the new speed unit setting
monkeytypegame/monkeytype pull request #4542
Opened 2023-08-15 01:22 UTC by ridemountainpig

### Description
Input history heatmap is add the new speed unit setting

wpm:

https://github.com/monkeytypegame/monkeytype/assets/92412722/03525c64-0543-4fc5-aeec-696cef589781

cpm:

https://github.com/monkeytypegame/monkeytype/assets/92412722/defc05c4-594c-4711-a5e7-8ee39a93aed5

wps:

https://github.com/monkeytypegame/monkeytype/assets/92412722/ccff5c0c-e590-46e0-864b-120f9e410573

cps:

https://github.com/monkeytypegame/monkeytype/assets/92412722/fee0261e-ec9f-4594-bb08-0302f9424846

Closes #4531

2023-08-15 01:26 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5862498133

2023-08-15 03:28 UTC, Pranay-Kamble approved these changes

2023-08-15 07:54 UTC, fehmer commented on frontend/src/ts/controllers/input-controller.ts
> +  TestInput.pushBurstToHistory(
Should we keep the data in wpm and only convert to the user defined unit when showing it to the user? The speed unit can be changed on the result screen as well.

2023-08-15 08:09 UTC, ridemountainpig commented on frontend/src/ts/controllers/input-controller.ts
> +  TestInput.pushBurstToHistory(
I think only changed speed unit on the result screen sound great, @Miodec how do you think, which way is better?

2023-08-15 08:36 UTC, ridemountainpig commented on frontend/src/ts/controllers/input-controller.ts
> +  TestInput.pushBurstToHistory(
I think change the data push to burst history is more better, if didn't change burst history just change speed unit on the result screen, there will have many `TestInput.burstHistory` in the code need to change also.

![CleanShot 2023-08-15 at 16 28 25@2x](https://github.com/monkeytypegame/monkeytype/assets/92412722/73e1895f-2092-4397-b252-908bdab9855e)

2023-08-15 10:24 UTC, fehmer commented on frontend/src/ts/controllers/input-controller.ts
> +  TestInput.pushBurstToHistory(
does the current solution supports switching the unit on the result screen p

2023-08-15 15:36 UTC, ridemountainpig commented on frontend/src/ts/controllers/input-controller.ts
> +  TestInput.pushBurstToHistory(
> Should we keep the data in wpm and only convert to the user defined unit when showing it to the user? The speed unit can be changed on the result screen as well.

@fehmer I have change the code to your provide solution, and the heatmap will change when switching the unit on the result screen using the command palette now.

https://github.com/monkeytypegame/monkeytype/assets/92412722/c6646c59-6671-454e-b0f6-3653d9eed641

2023-08-17 05:03 UTC, fehmer commented on frontend/src/ts/config.ts
> +  applyBurstHeatmap();
We should not call it here. There is an event triggered when updating the typingSpeedUnit and you can listen on that event on the result screen

2023-08-17 05:04 UTC, fehmer requested changes

2023-08-17 05:04 UTC, fehmer commented on frontend/src/ts/config.ts
> +  applyBurstHeatmap();
We should not call it here. There is an event triggered when updating the typingSpeedUnit and you can listen on that event on the result screen

2023-08-17 05:51 UTC, ridemountainpig commented on frontend/src/ts/config.ts
> +  applyBurstHeatmap();
I have update it in new commit.

2023-08-17 06:32 UTC, fehmer commented
display for wps causes problems:
![image](https://github.com/monkeytypegame/monkeytype/assets/3728838/f4f1033c-ea39-4647-a816-d26c522fb893)

We could use steps of `0.5` as we do with the histogram chart on the accounts page.

2023-08-17 06:42 UTC, ridemountainpig commented
<img width="1197" alt="CleanShot 2023-08-17 at 14 40 22@2x" src="https://github.com/monkeytypegame/monkeytype/assets/92412722/507c70c7-7ea3-4b17-9e45-68c30842ef0a">

I think it look good right now.

2023-08-17 10:30 UTC, Miodec commented
> display for wps causes problems: ![image](https://user-images.githubusercontent.com/3728838/261218307-f4f1033c-ea39-4647-a816-d26c522fb893.png)
> 
> We could use steps of `0.5` as we do with the histogram chart on the accounts page.

Idk, even with 0.5 there just isnt enough resolution, just the drawback of wps.

2023-08-17 10:46 UTC, Miodec requested changes

2023-08-17 10:46 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
> +        getTypingSpeedUnit(Config.typingSpeedUnit).fromWpm(burst)
Maybe extract the speed unit outside of the loop? Then only call `fromWpm` inside the loop.

2023-08-17 10:46 UTC, Miodec commented on frontend/src/ts/test/result.ts
> +    TestUI.applyBurstHeatmap();
Will this apply the heatmap even if its disabled? Or only when its visible?

2023-08-17 10:46 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
> +        let wordBurstVal = parseInt(<string>wordBurstAttr);
Could you just change `<string>` to `to string`? We don't really use this syntax often. (But i know its not your change)

2023-08-17 11:08 UTC, ridemountainpig commented on frontend/src/ts/test/result.ts
> +    TestUI.applyBurstHeatmap();
It will run when user change speed unit.

2023-08-17 11:09 UTC, Miodec commented on frontend/src/ts/test/result.ts
> +    TestUI.applyBurstHeatmap();
Yes, i know. But what if the heatmap is not enabled? Will this automatically enable it?

2023-08-17 11:30 UTC, ridemountainpig commented on frontend/src/ts/test/result.ts
> +    TestUI.applyBurstHeatmap();
It will only run when user change speed unit in after test result page, in other page won't.

2023-08-17 11:40 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5890394588

2023-08-17 12:22 UTC, merged