Added 3 texts in spanish.json
monkeytypegame/monkeytype pull request #4591
Opened 2023-08-27 15:08 UTC by KANGRIZ

One of the texts is long, and the other two are short.  Id: 142, 143 and 144

### Description

Closes #

2023-08-27 15:10 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5991687204

2023-08-27 15:29 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5991774274

2023-08-27 15:34 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5991796242

2023-08-27 15:40 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/5991823960

2023-08-27 15:49 UTC, KANGRIZ commented
three Spanish texts were added to the spanish.json document. In addition to some changes in spelling and punctuation.

2023-08-28 09:58 UTC, Miodec requested changes
Please leave a comment with translations so I can verify their content.

2023-08-28 09:58 UTC, Miodec commented on frontend/static/quotes/spanish.json
> +      "text": "Existen otros centenares de ellos tan pequeños a veces, que es difícil distinguirlos aún con la ayuda del telescopio. Cuando un astrónomo descubre uno de estos planetas, le da por nomb
Missing period at the end of the quote.

2023-08-28 22:33 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6005623272

2023-09-01 23:34 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6054890531

2023-09-01 23:46 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6054947115

2023-09-01 23:47 UTC, KANGRIZ commented
Hi!

2023-09-01 23:49 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6054961831

2023-09-01 23:59 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6054996821

2023-09-02 00:12 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6055076776

2023-09-02 00:18 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6055116580

2023-09-04 23:45 UTC, closed without merging