Feat: malay1k
monkeytypegame/monkeytype pull request #4607
Opened 2023-09-04 13:47 UTC by kopipahit-1

Added malay_1k.json for Bahasa Malaysia.

2023-09-04 13:50 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6074308979

2023-09-04 16:47 UTC, Miodec requested changes

2023-09-04 16:47 UTC, Miodec commented on frontend/static/languages/malay_1k.json
> +  "name": "malay",
This needs to match filename (`malay_1k`)

2023-09-04 16:47 UTC, Miodec commented on frontend/static/languages/malay.json
> -    "ada",
This pr still edits the `malay.json` file, when it should only be adding the `1k` file.

2023-09-04 17:52 UTC, kopipahit-1 reviewed
changes  "name": "malay", to "malay_1k".

Thank you.

2023-09-04 18:12 UTC, kopipahit-1 reviewed
Deleted malay.json file.

2023-09-04 18:14 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6076550419

2023-09-05 13:41 UTC, Miodec commented
You need to revert the changes instead of deleting it.

2023-09-08 18:09 UTC, kopipahit-1 reviewed
Revert it. Thank you for the guide.

2023-09-08 18:11 UTC, kopipahit-1 reviewed
Revert it.

2023-09-08 18:12 UTC, kopipahit-1 reviewed
Revert it.

2023-09-09 10:47 UTC, kopipahit-1 reviewed
Re

2023-09-11 17:41 UTC, Miodec commented
Thanks

2023-09-11 17:41 UTC, merged