New language - Irish 1k
monkeytypegame/monkeytype pull request #4610
Opened 2023-09-07 08:37 UTC by EoinSMC

### Description

Closes #

2023-09-07 08:40 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6107421846

2023-09-09 15:17 UTC, Shuja-Mahmood requested changes
I've reviewed your code and left a few comments to help out.

2023-09-09 15:17 UTC, Shuja-Mahmood commented on frontend/static/languages/irish_1k.json
> +  "name": "irish_",
```suggestion
  "name": "irish_1k",
```

2023-09-09 15:17 UTC, Shuja-Mahmood commented on frontend/static/languages/irish_1k.json
> +    "aimsiú",
```suggestion
    "aimsiú"
```
`ci-assets` failing due to this

2023-09-09 15:17 UTC, Shuja-Mahmood commented on frontend/static/languages/_groups.json
> +    ]
```suggestion
    "languages": [
      "irish",
      "irish_1k"
    ]
```
Let's match the indent with the rest of the file.

2023-09-26 20:34 UTC, closed without merging