feat: Addition of Stt Units
monkeytypegame/monkeytype pull request #4633
Opened 2023-09-14 15:00 UTC by Perseus333

This PR adds the unit Stt (Seconds to Type) to the choosable typing units. STT is a unit which is measured in seconds of how long does it take you to type a 100 word (500 character) text.  It's a unit that is intended to see the real time saving or progress that you are archieving with your speed improvements. For more information see [this desmos](https://www.desmos.com/calculator/objfzho0ss).

2023-09-14 15:02 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6187283763

2023-09-14 15:05 UTC, fehmer commented
i think you're missing a change in the `backend/src/api/schemas/config-schema.ts` to account for the new  unit string

2023-09-14 15:07 UTC, fehmer commented
do we want to add this unit to the settings page as well? `frontend/static/html/pages/settings.html`

2023-09-14 15:17 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6187477326

2023-09-14 15:28 UTC, Perseus333 commented
> i think you're missing a change in the `backend/src/api/schemas/config-schema.ts` to account for the new unit string

oh, could be, since I did changes on frontend

2023-09-14 15:43 UTC, Perseus333 commented
> do we want to add this unit to the settings page as well? `frontend/static/html/pages/settings.html`

yeah I think so

2023-09-14 18:23 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6189394787

2023-09-18 13:47 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6223417215

2023-09-18 14:16 UTC, Miodec commented
Account page is broken, please investigate.

2023-09-19 08:14 UTC, fehmer requested changes

2023-09-20 13:26 UTC, Perseus333 commented on frontend/src/ts/utils/typing-speed-units.ts
> -    return wpm * this.convertFactor;
It may have been creaated by prettify

2023-09-21 11:00 UTC, Miodec commented on frontend/src/ts/utils/typing-speed-units.ts
> -    return wpm * this.convertFactor;
Prettify doesn't add code, it only modifies formatting.

2023-11-07 20:34 UTC, closed without merging