chore: update jQuery to 3.7.1
monkeytypegame/monkeytype pull request #4649
Opened 2023-09-20 14:56 UTC by fehmer

Update jQuery to 3.7.1.

I used the [jQuery Migrate](https://github.com/jquery/jquery-migrate#migrate-older-jquery-code-to-jquery-30) plugin to check for needed migrations.

2023-09-20 15:20 UTC, fehmer commented on frontend/static/js/easing.min.js
rename to easing-1.4.1.min.js

2023-09-21 11:00 UTC, Miodec requested changes

2023-09-21 11:00 UTC, Miodec commented on frontend/static/js/easing-1.4.1.min.js
> +(function(factory){if(typeof define==="function"&&define.amd){define(["jquery"],function($){return factory($)})}else if(typeof module==="object"&&typeof module.exports==="object"){exports=factory(req
Did you only add the version number here or did you actually change the code?

2023-09-21 11:14 UTC, fehmer commented on frontend/static/js/easing-1.4.1.min.js
> +(function(factory){if(typeof define==="function"&&define.amd){define(["jquery"],function($){return factory($)})}else if(typeof module==="object"&&typeof module.exports==="object"){exports=factory(req
I updated the code from the unknown version to the latest 1.4.1. The migrate plugin was logging deprecated usage of things from this lib.

2023-09-21 12:06 UTC, merged