fix: language selection scroll into view
monkeytypegame/monkeytype pull request #4663
Opened 2023-09-25 11:01 UTC by JayTailor45

### Description
It improves language selection dropdown by adding scroll into view. Now selected values will be automatically scrolled into view.

Closes #4662

https://github.com/monkeytypegame/monkeytype/issues/4662

2023-09-25 11:20 UTC, Miodec requested changes
Please remove the animation and only animate if the `$("#commandLine input").val()` is empty, otherwise scroll to top.

2023-09-25 12:09 UTC, JayTailor45 commented
@Miodec I have updated the code. Now my function looks like this. Can you please let me know best way to test both cases?

```ts
function scrollSelectedLanguageToView(): void {
  const suggestions = $(".suggestions");
  const scrollTarget = $(".suggestions .entry .icon i.fa-check");
  if (suggestions.length && scrollTarget.length) {
    const paddingOffset = 8;
    const suggestionsOffset = suggestions.offset();
    const scrollTargetOffset = scrollTarget.offset();
    if (suggestionsOffset && scrollTargetOffset) {
      if (!$("#commandLine input").val()) {
        $(".suggestions").animate(
          {
            scrollTop:
              scrollTargetOffset.top - suggestionsOffset.top - paddingOffset,
          },
          500
        );
      } else {
        $(".suggestions").scrollTop(
          scrollTargetOffset.top - suggestionsOffset.top - paddingOffset
        );
      }
    }
  }
}
```

2023-09-25 13:28 UTC, Miodec commented
The animation is still there and the element is still scrolled to the top instead of the center.

2023-09-25 13:29 UTC, Miodec commented
The results are also not scrolled to the top.

2023-09-26 07:58 UTC, JayTailor45 commented
@Miodec I've made changes as you mentioned. Please check it and let me know if any changes require. Thanks!

> Steps to test with:
> 
> Set language to `russian`. Open the commandline, go to the language selection. The results should snap to russian being in the middle. (currently `russian` is begin snapped to the top) As soon as i start typing, for example wanting to switch to `spanish`, the results should snap to the top (currently after pressing `s`, they are still scrolled down)

2023-09-26 12:50 UTC, Miodec commented
Another issue is that if you scroll the list to the currently active element, the selected element is still the first one, making it a bit confusing.

2023-09-26 13:17 UTC, JayTailor45 commented
Oh I thought it was intentional. Now worries. I will make the change ;) 
> Another issue is that if you scroll the list to the currently active element, the selected element is still the first one, making it a bit confusing.

2023-09-27 06:38 UTC, JayTailor45 commented
@Miodec I've added the active element logic as you asked. Please check it and let me know. also let me know if you need squashed commit. Thanks!

> Another issue is that if you scroll the list to the currently active element, the selected element is still the first one, making it a bit confusing.

2023-10-02 12:55 UTC, Miodec requested changes

2023-10-02 12:55 UTC, Miodec commented on frontend/src/ts/commandline/index.ts
> +    const scrollTarget = $(".suggestions .entry .icon i.fa-check");
It looks like this `.suggestions .entry .icon i.fa-check` element is used both here and in `updateSuggested`. I think instead of always scrolling the checked element into view, we convert this function to be a more generic `scrollActiveEntryToCenter()` which scrolls an entry to center which has an index of `activeIndex` (global variable in this file)

Also, i would move the `if ($("#commandLine input").val())` check to the `updateSuggested()` funciton aswell.

2023-10-02 12:57 UTC, Miodec commented on frontend/src/ts/commandline/index.ts
> +    const scrollTarget = $(".suggestions .entry .icon i.fa-check");
I just realised there is a function for that already - `keepActiveEntryInView()`. I think this whole function is not needed.

2023-10-02 14:00 UTC, JayTailor45 commented
@Miodec thanks for the feedback. I have refactored the code to use the existing `keepActiveEntryInView()`.

2023-10-02 14:30 UTC, Miodec commented
Well done, thanks.

2023-10-02 14:31 UTC, merged

2023-10-02 16:11 UTC, JayTailor45 commented
My pleasure! Thank you for the opportunity.