Impr: Added 6 more quotes.
monkeytypegame/monkeytype pull request #4675
Opened 2023-09-27 21:02 UTC by aikooo7

### Description

I have added six English quotes to the project.

My pull request includes six quotes that I found during a search, and they are in English.

2023-09-27 21:04 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6331395328

2023-09-29 13:08 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "In the depth of winter, I finally learned that there was in me an invincible summer",
Missing period

2023-09-29 13:08 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "In the depth of winter, I finally learned that there was in me an invincible summer",
Also probably change to `that there was an invincible summer in me`

2023-09-29 13:09 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7000
Bit too short imo. Use a longer version if available or remove.

2023-09-29 13:10 UTC, Miodec requested changes
Some things to update

2023-09-29 17:25 UTC, aikooo7 commented on frontend/static/quotes/english.json
> +      "id": 7000
Added bigger quote, let me you know if you want a bigger and if so size would help.

2023-09-29 17:25 UTC, aikooo7 commented on frontend/static/quotes/english.json
> +      "text": "In the depth of winter, I finally learned that there was in me an invincible summer",
Done everything, appreciate your help.

2023-09-29 17:27 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6354966470

2023-09-29 17:29 UTC, aikooo7 commented
Just a note, my bad for all the quote size commits, sadly I always get it wrong, that ci for checking json is a really good feature.

2023-10-02 14:17 UTC, Miodec approved these changes

2023-10-02 14:17 UTC, merged