impr: modified typing error sound code to support multiple options and added two alternate error sounds
monkeytypegame/monkeytype pull request #4679
Opened 2023-09-29 09:05 UTC by W0LFB0MB

### Description

Modified the typing error sound code (when you make a typo) to support multiple options and added two alternate error sounds. The old sound is named damage as it sounds like getting hit in a videogame and the new sounds are named square and triangle after the wave used to create them.

Note: as I don't use MongoDB regularly, I am unsure as what will occur with the datatypes switching from boolean to string when previous users log on / change their settings.

2023-09-30 06:23 UTC, W0LFB0MB commented
Tested whether old users of the feature would recieve errors (they did) and added a few lines of code to fix that.
also checked if saving a string value to a previously boolean entry broke anything and it didnt so big success.

2023-10-02 14:23 UTC, Miodec requested changes

2023-10-02 14:23 UTC, Miodec commented on frontend/src/ts/config.ts
> +  }
There is a dedicated `replaceLegacyValues` function which handles things like this. Move this code there please.

2023-10-02 14:54 UTC, W0LFB0MB commented on frontend/src/ts/config.ts
> +  }
All done 👍

2023-10-02 15:09 UTC, merged

2023-10-02 15:09 UTC, Miodec commented
Thanks