Feature: Adding intellij darcula theme
monkeytypegame/monkeytype pull request #4713
Opened 2023-10-09 23:22 UTC by manuelzzz

## Making a functional intellij darcula theme.

### My base theme was:
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/0a0bdd6f-d26c-4b90-bd0c-31b257e245f2)

## After implements in .css file on project:
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/cc550abe-edcc-4edf-8332-287c996a38bc)
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/d33c5d50-970b-43d9-a57f-463931925ef6)
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/5e84b7ae-9b4c-43b4-8f6f-5ff46476ffc4)
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/fc498140-36ae-45f8-9ca2-6328bb3e87a2)

### note: Thats my first time making a pr in open-sources projects and i use the monkeytype every day, so, nothing better then that
### i hope you all like :)

2023-10-10 10:31 UTC, Miodec requested changes
<img width="946" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/a6a56565-7dcb-4977-84bd-91fc11911f4d">

Not the best color choice so far, sub alt color cannot be this light - it should be much closer to the bg color. Also the contrast between text and sub color is too low. I would also swap text and sub around.

Please use other themes as your guide as to what which colors play what role.

2023-10-10 10:31 UTC, Miodec commented on frontend/static/themes/_list.json
> +    "name": "intellij darcula",
Names must be the same as file names. Replace the space with an underscore

2023-10-10 12:14 UTC, manuelzzz commented
I think that is more acceptable
![image](https://github.com/monkeytypegame/monkeytype/assets/89389164/9295642a-a9aa-417f-9146-80498203c6df)

2023-10-11 11:20 UTC, Miodec commented
Text color cannot be colored. It needs to be close to white or black (can have a slight tint).

2023-10-12 00:59 UTC, manuelzzz commented
If i invert the sub and text colors make sense? becouse that exactly the color pallet

2023-10-12 10:26 UTC, Miodec commented
It may be better. But i stil havent checked for similar themes that are already available.

2023-10-16 13:09 UTC, Miodec commented
I think the sub and main colors are too simmilar to each other.

2023-10-21 15:16 UTC, manuelzzz commented
Okay, i will change to better

2023-11-06 20:34 UTC, closed without merging