feat: Allow more results for premium users
monkeytypegame/monkeytype pull request #4767
Opened 2023-11-06 08:20 UTC by fehmer

### Description

- add `limit` and `offset` to `/results` endpoint
- add result limitation for regular and premium users to server configuration
- extend user with  `isPremium` flag.

2023-11-06 13:14 UTC, Miodec requested changes

2023-11-06 13:14 UTC, Miodec commented on backend/src/api/controllers/user.ts
> +    );
I think the `isPremium` should be added in `UserDAL.getUser` instead of here.

2023-11-06 13:14 UTC, Miodec commented on backend/src/types/types.d.ts
> +    isPremium?: boolean;
As mentioned on Discord, this should be an object so its more easily expandable in the future with more parameters.

2023-11-06 13:14 UTC, Miodec commented on backend/src/dal/user.ts
> +}
Whats the point of passing the whole user object to this function just to check the isPremium property?

2023-11-06 13:14 UTC, Miodec commented on backend/src/api/controllers/result.ts
>    return new MonkeyResponse("Results retrieved", results);
The controller should ensure at some point that the we will not request more than 1000 results at once. Currently you can give an offset of 0 and max limit, which would cause a large query (possibly up to 25k results) and a massive response (possibly even going over some limits).

2023-11-06 15:44 UTC, fehmer commented on backend/src/api/controllers/user.ts
> +    );
done.

2023-11-06 15:45 UTC, fehmer commented on backend/src/dal/user.ts
> +}
Removed.

2023-11-06 15:46 UTC, fehmer commented on backend/src/api/controllers/result.ts
>    return new MonkeyResponse("Results retrieved", results);
max limit is 1000 or the configured limit on the server config now  (whatever is lower). Updated the rate-limiter to allow 30 requests to `/results` per day now so apeKey users can use the pagination as well.

2023-11-07 15:36 UTC, Miodec requested changes

2023-11-07 15:36 UTC, Miodec commented on backend/__tests__/dal/result.spec.ts
> +      expect(results).toHaveLength(30);
getResults is limited to 1000, the test says it should "read all". I would update the test name.

2023-11-07 15:36 UTC, Miodec commented on backend/__tests__/api/controllers/result.spec.ts
> +    });
Shouldnt it fail for *any* user when exceeding the 1k limit? Since we are limiting pagination to 1000?

2023-11-07 15:36 UTC, Miodec commented on backend/src/api/controllers/result.ts
> +
This can return `NaN` if you give it a non number string (eg "test")

2023-11-07 15:36 UTC, Miodec commented on backend/src/api/controllers/result.ts
> +    throw new MonkeyError(422, `max results of ${maxLimit} exceeded.`);
Update message to `Max results limit of ${maxLimit} esceeded.` Dont forget to update tests.

2023-11-07 15:40 UTC, Miodec commented on backend/src/api/routes/results.ts
> +      limit: joi.number().integer().min(0).max(1000),
Limit can be 0. Does it mean Mongodb will try to pull as many results as possible?

2023-11-07 15:40 UTC, Miodec commented on backend/src/api/routes/results.ts
> +      limit: joi.number().integer().min(0).max(1000),
Nevermind. Mongo will return an empty set.

2023-11-07 15:50 UTC, fehmer commented on backend/__tests__/dal/result.spec.ts
> +      expect(results).toHaveLength(30);
getResults is limited on the controller to a max limit of 1k, the Dal does not have this restriction.

2023-11-07 20:37 UTC, fehmer commented on backend/__tests__/api/controllers/result.spec.ts
> +    });
done

2023-11-07 20:37 UTC, fehmer commented on backend/src/api/controllers/result.ts
> +
done

2023-11-07 20:37 UTC, fehmer commented on backend/src/api/controllers/result.ts
> +    throw new MonkeyError(422, `max results of ${maxLimit} exceeded.`);
done

2023-11-08 00:39 UTC, Bruception commented on backend/src/types/types.d.ts
> +  }
is there a spec for this feature?
Think it would make more sense to store a timestamp here, and provide utilities in app code to determine if a user's premium is active.

```suggestion
  interface PremiumInfo {
    expirationTimestamp: number;
  }
```

2023-11-08 00:42 UTC, Bruception commented on backend/src/types/types.d.ts
> +  }
Maybe even include start timestamp?

2023-11-08 00:43 UTC, Bruception commented on backend/src/types/types.d.ts
> +    isPremium?: boolean;
I think maintaining `isPremium` and `premium` is a bit tricky.
We should just rely on presence/absence of premium field.
If premium membership is expired, we can inspect the `premium` object.

2023-11-08 00:47 UTC, Bruception commented on backend/src/types/types.d.ts
> +  }
perhaps even a `type` field if we want to support tiered memberships, but that would have a huge change on your overall implementation.

2023-11-09 15:35 UTC, Bruception commented on backend/src/types/types.d.ts
> +  interface PremiumInfo {
start timestamp?

2023-11-09 15:50 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6814154301

2023-11-09 15:57 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6814231662

2023-11-09 16:05 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6814231662

2023-11-10 13:55 UTC, merged