Semantic HTML (borisnezlobin)
monkeytypegame/monkeytype pull request #4859
Opened 2023-12-12 03:34 UTC by borisnezlobin

### Description
Changes the HTML to be more semantic (e.g., changing `<div class="section">` to just `<section>`)
This PR currently only changes one page (`/about`) in order to get progress feedback before changes are made to everything.

### Checks
No visual changes
- [x] Adding a language or a theme?
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
    - #4857 
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #4857

2023-12-14 11:37 UTC, Miodec requested changes

2023-12-14 11:37 UTC, Miodec commented on frontend/static/html/pages/about.html
> +    <h1 class="bigtitle">about</h1>
Use h2 here, then you can remove the bigtitle class

2023-12-14 11:37 UTC, Miodec commented on frontend/static/html/pages/about.html
>      <div class="title">word set</div>
Use h3, then remove the title class

2023-12-14 11:38 UTC, Miodec commented on frontend/static/html/pages/about.html
>      <div class="title">word set</div>
Also use h3 everywhere where you already used h2

2023-12-14 19:47 UTC, borisnezlobin commented
Will do!
should I apply these changes everywhere else then?

2023-12-15 10:48 UTC, Miodec commented
Everywhere else you mean other pages?

2023-12-15 14:20 UTC, borisnezlobin commented
yep!

2023-12-15 14:20 UTC, Miodec commented
Yeah sure

2023-12-17 18:20 UTC, fehmer commented
hi @borisnezlobin, 
can you add ids to all headers so they can be used as anchors in links?

2023-12-18 17:00 UTC, borisnezlobin commented
Will do! I have finals this week, but will be able to work on this later this week + next

2024-01-13 20:33 UTC, closed without merging