added quotes in english and dutch
monkeytypegame/monkeytype pull request #4898
Opened 2024-01-02 17:38 UTC by J4spr

### Description

### Checks

- [ ] Adding a language or a theme?
    - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
    - [ ] If is a theme, did you add the theme.css?
        - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

2024-01-02 17:40 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7388780646

2024-01-08 14:12 UTC, Miodec requested changes

2024-01-08 14:12 UTC, Miodec commented on frontend/static/quotes/dutch.json
> +      "text": "Zelf iets oplossen wil niet zeggen dat je het alleen moet doen.",
Please provide a translation

2024-01-08 14:12 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7029
All of them have misspelled "length". Also most of them are too short (60 characters minimum please). Also some are missing a punctuation at the end.

2024-02-03 04:32 UTC, NipulM commented on frontend/static/quotes/dutch.json
> +      "text": "Zelf iets oplossen wil niet zeggen dat je het alleen moet doen.",
It translates to "Solving something by yourself doesn't mean you have to do it alone." in English.

2024-03-01 20:34 UTC, closed without merging