impr(quotes): add 8 new English quotes (LifeAdventurer)
monkeytypegame/monkeytype pull request #4916
Opened 2024-01-12 03:47 UTC by LifeAdventurer

2024-01-15 11:41 UTC, Miodec requested changes

2024-01-15 11:41 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7027
Remove, seems a bit weird without some context.

2024-01-15 11:41 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Life is in a land full of thorns and weeds, there always a space in which the good seed can grow.",
Seems like there is a "but" missing? "but there's" ?

2024-01-15 11:41 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Loss is nothing else but change, and change is nature's delight.",
Remove

2024-01-15 13:38 UTC, LifeAdventurer commented on frontend/static/quotes/english.json
> +      "text": "Life is in a land full of thorns and weeds, there always a space in which the good seed can grow.",
I checked it, and there is a "is" missing, but no "but" missing.

2024-01-15 13:38 UTC, LifeAdventurer commented on frontend/static/quotes/english.json
> +      "text": "Loss is nothing else but change, and change is nature's delight.",
May I know why? I can be more careful next time and know how to choose.

2024-01-15 13:40 UTC, LifeAdventurer commented on frontend/static/quotes/english.json
> +      "id": 7027
I have seen this quote from many websites.
https://www.goodreads.com/quotes/427330-if-there-is-magic-on-this-planet-it-is-contained
https://themeaningofwater.com/2014/12/01/water-is-magic/
https://www.azquotes.com/quote/87464

2024-01-15 14:47 UTC, NipulM commented on frontend/static/quotes/english.json
> +      "text": "Life is in a land full of thorns and weeds, there always a space in which the good seed can grow.",
The only similar quote I found, with a length of 125 characters, is: "Although the life of a person is in a land full of thorns and weeds, there is always a space in which the good seed can grow."

2024-01-15 14:55 UTC, LifeAdventurer commented on frontend/static/quotes/english.json
> +      "text": "Life is in a land full of thorns and weeds, there always a space in which the good seed can grow.",
yeah, it's the same one. I saw "Life is in a land full of thorns and weeds, there is always a space in which the good seed can grow." on an app.

maybe I'll change it to this one. thanks~

2024-01-15 16:53 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Loss is nothing else but change, and change is nature's delight.",
Just don't really like its content. Hard to explain.

2024-01-15 17:10 UTC, LifeAdventurer commented on frontend/static/quotes/english.json
> +      "text": "Loss is nothing else but change, and change is nature's delight.",
okay, I removed it

2024-01-16 12:50 UTC, NipulM approved these changes
Reviewed the quotes, and they check out. Lengths match as specified. All good!

2024-01-16 12:58 UTC, LifeAdventurer commented
Thanks for reviewing my pull request.

2024-01-18 09:51 UTC, Miodec approved these changes

2024-01-18 09:51 UTC, Miodec commented
Please resolve conflict

2024-01-18 09:51 UTC, Miodec commented
> Reviewed the quotes, and they check out. Lengths match as specified. All good!

Just so you know you don't need to check lengths yourself, they are checked automatically.

2024-01-18 10:18 UTC, LifeAdventurer commented
> Please resolve conflict

Resolved

2024-01-18 10:42 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7568770486

2024-01-18 10:44 UTC, LifeAdventurer commented
> Please resolve conflict

resolved

2024-01-18 14:03 UTC, merged