refactor: quotes types (zaitsev-oleksii)
monkeytypegame/monkeytype pull request #4981
Opened 2024-01-29 22:16 UTC by zaitsev-oleksii

### Description

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

related to https://github.com/monkeytypegame/monkeytype/issues/4786

2024-01-29 22:19 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7703190965

2024-01-30 12:58 UTC, Miodec requested changes

2024-01-30 12:58 UTC, Miodec commented on frontend/src/ts/ape/types/quotes.d.ts
> +  type PostReport = void;
Replace `void` with `null`

2024-01-30 16:42 UTC, Miodec commented on frontend/src/ts/ape/types/ape.d.ts
>  }
Also, why are these changes needed?

2024-01-30 19:59 UTC, zaitsev-oleksii commented on frontend/src/ts/ape/types/ape.d.ts
>  }
Without making HttpClient methods generic getting type errors here
Do you have any ideas on how I can fix those in a better way?

![image](https://github.com/monkeytypegame/monkeytype/assets/81097502/a5157233-98b2-490c-8a25-a86a23b998c5)

2024-01-30 20:25 UTC, Miodec commented on frontend/src/ts/ape/types/ape.d.ts
>  }
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/b0662557-ee55-4378-a812-96a49625df47)

2024-01-30 20:39 UTC, zaitsev-oleksii commented on frontend/src/ts/ape/types/ape.d.ts
>  }
okay, thank you, will make changes

2024-01-30 20:45 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/7717215110

2024-01-30 21:32 UTC, Miodec approved these changes
Thanks

2024-01-30 21:33 UTC, merged