impr(quotes): Added a few more quotes to the list!
monkeytypegame/monkeytype pull request #5066
Opened 2024-02-16 01:02 UTC by CedricBaaklini

I took the liberty to add a few quotes onto the JSON file for the English language from various pop culture media.

2024-02-19 13:27 UTC, Miodec commented
Your PR includes a theme. Please remove unrelated changes.

2024-02-19 13:27 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7034
Also, these quotes are too short.

2024-02-19 13:28 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7031
Inconsistent capitalisation in these quotes. 'God' is sometimes capitalised sometimes not. Why is 'truth' capitalised?

2024-02-21 05:02 UTC, CedricBaaklini commented on frontend/static/quotes/english.json
> +      "id": 7031
That was just how the script was written, but I can fix it if you like.

2024-02-22 10:52 UTC, Miodec requested changes

2024-02-22 10:52 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "id": 7031
Duplicate of quote `6562`. Please check for duplicates before adding quotes.

2024-02-22 10:54 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8003299821

2024-02-26 12:28 UTC, Miodec approved these changes

2024-02-26 12:29 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Rorschach’s Journal. October 12th, 1985: Dog carcass in alley this morning, tire tread on burst stomach. This city is afraid of me. I have seen its true face. The streets are extended
It mentions a dead dog in an alley? Not the best choice.

2024-02-26 19:48 UTC, CedricBaaklini commented on frontend/static/quotes/english.json
> +      "text": "Rorschach’s Journal. October 12th, 1985: Dog carcass in alley this morning, tire tread on burst stomach. This city is afraid of me. I have seen its true face. The streets are extended
Wait, you guys don't even want references of death?

2024-02-27 18:49 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "Rorschach’s Journal. October 12th, 1985: Dog carcass in alley this morning, tire tread on burst stomach. This city is afraid of me. I have seen its true face. The streets are extended
Kids use this site, so i prefer to keep it without much details.

2024-02-28 13:13 UTC, Miodec commented
Please merge master in and resolve conflicts.

2024-02-29 06:14 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8091815895

2024-04-06 20:34 UTC, closed without merging