impr(quotes): add French quotes
monkeytypegame/monkeytype pull request #5111
Opened 2024-02-23 12:49 UTC by Ratipoka

### Description

I've added 1 french quote from Les Liaisons Dangereuses [ebook](https://www.ebooksgratuits.com/ebooksfrance/laclos_liaisons_dangereuses.pdf) and I have corrected some sources : the Author and the name of the book was mixed up.

translation : 
"If, however, you have seen me, disposing of events and opinions, make of these men so formidable the plaything of my whims or my fancies; depriving some of the will, others of the power to harm me; if I have known how to alternately, and according to my mobile tastes, attach to my retinue or reject far from me
Those dethroned tyrants who have become my slaves
if, in the midst of these frequent revolutions, my reputation has nonetheless remained pure; must you not have concluded that, born to avenge my sex and subdue yours, I was able to create for myself means hitherto unknown to me?"

### Checks

- [X] Adding quotes?
  - [X] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

2024-02-23 12:51 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8019435563

2024-02-23 12:54 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8019476939

2024-02-26 12:18 UTC, Miodec requested changes

2024-02-26 12:18 UTC, Miodec commented on frontend/static/quotes/french.json
> +      "source": "Pierre Choderlos de Laclos - Les Liaisons Dangereuses (Lettre LXXXI)",
I wouldn't use `\n`.

2024-03-11 20:34 UTC, closed without merging

2024-03-24 14:29 UTC, Ratipoka commented on frontend/static/quotes/french.json
> +      "source": "Pierre Choderlos de Laclos - Les Liaisons Dangereuses (Lettre LXXXI)",
Is it specific to the quote or is using `\n` generally deprecated for all quotes ? I found other quotes using `\n` in this file.

I Think the `\n` are relevant here for this specific quote because
- There is a line return in the original quote
- The part of the quote that is on a new line is really the most dramatic, so it makes sense to do something to highlight it.

But yeah, maybe the capital letters are enough emphasis.