impr: better handling of ghost accounts
monkeytypegame/monkeytype pull request #5159
Opened 2024-02-29 15:52 UTC by fehmer

### Description

Fixes #4909.

2024-02-29 22:24 UTC, Miodec requested changes

2024-02-29 22:24 UTC, Miodec commented on frontend/src/ts/popups/simple-popups.ts
> +    Notifications.add("Deleting user...", 0);
I would change to something like `Deleting all data...`

2024-03-01 08:56 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8108857745

2024-03-02 14:44 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8123489857

2024-03-02 16:48 UTC, FFUV commented
what does it mean by dealing with ghost accounts?

2024-03-03 12:11 UTC, fehmer commented
build errors are unrelated and fixed with https://github.com/monkeytypegame/monkeytype/pull/5166

2024-03-04 13:23 UTC, Miodec approved these changes
Thanks

2024-03-04 13:23 UTC, merged