impr(quotes): Adding Swift Quotes File.
monkeytypegame/monkeytype pull request #5161
Opened 2024-02-29 19:57 UTC by CedricBaaklini

I've noticed that there is no quotes for Swift and as someone who loves Swift and uses it as their primary language, I'm a little disappointed that there is no quote file for Swift. So, I decided to make one myself and added a few quotes to get started, including a "Hello World" Program. Feel free to let me know if there are any errors or improvements to be made.

2024-02-29 20:00 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8101848500

2024-02-29 22:22 UTC, Miodec requested changes

2024-02-29 22:22 UTC, Miodec commented on frontend/static/quotes/test.ts
Remove this please

2024-02-29 22:22 UTC, Miodec commented on frontend/static/quotes/code_swift.json
Could you please add more quotes? It would greatly reduce repetition

2024-02-29 23:13 UTC, CedricBaaklini commented on frontend/static/quotes/code_swift.json
Sure thing. Like I said in the message, it is just a few to get started.

2024-02-29 23:16 UTC, CedricBaaklini commented on frontend/static/quotes/code_swift.json
It would be nice for more people to help out add quotes into the file.

2024-02-29 23:18 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8103907201

2024-02-29 23:22 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8103952927

2024-03-01 18:50 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8115827165

2024-03-06 18:47 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8177153147

2024-03-06 19:14 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8177470246

2024-03-08 21:04 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8208980663

2024-03-10 19:23 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8224246235

2024-03-25 18:46 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8425326176

2024-04-09 20:34 UTC, closed without merging