impr(quotes): add Hebrew quotes
monkeytypegame/monkeytype pull request #5262
Opened 2024-03-28 20:31 UTC by ItsBenDov

- [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.

"Violence is eroding the foundation of Israeli democracy. She must be condemned, denounced, isolated."

"Make you a rabbi, and buy you a friend, and he will judge the whole person to a rightful place - odd translation, sounds better in hebrew."

"Honesty is strength, values are strength, cunning and corruption bring us down, generosity and love are the strongest forces in the world"

"what? No way?!" a very famous quote in israel, again, sounds better in Hebrew.

"There will be nothing, because there is nothing"

Thank you!

2024-03-28 20:34 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8473333369

2024-04-03 10:15 UTC, Miodec commented on frontend/static/quotes/hebrew.json
> +    },
Way too short, please remove or use a longer version.

2024-04-03 16:41 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8542359962

2024-04-03 20:26 UTC, Miodec requested changes
Update short quotes with longer versions (quotes should be at least 60 characters)

Also please update translations.

2024-04-08 10:18 UTC, Miodec approved these changes

2024-04-08 10:19 UTC, merged