Fixed quote source.
monkeytypegame/monkeytype pull request #5361
Opened 2024-05-04 04:38 UTC by triach-rold

### Description

Just gave the credits to the original author of the quote. This is a common misattribution. [Source](https://www.goodreads.com/quotes/467-life-is-what-happens-to-us-while-we-are-making).

2024-05-04 04:45 UTC, triach-rold commented
Added a new quote from Friedrich Nietzsche.

2024-05-07 10:14 UTC, triach-rold commented on frontend/static/quotes/english.json
> +      "id": 7059
You're right. I've fixed the punctuation @Miodec !

2024-05-07 10:15 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/8983579016

2024-05-08 12:34 UTC, Miodec commented
Please fix incorrect quote length and PR title

2024-05-14 20:38 UTC, triach-rold commented
> Please fix incorrect quote length and PR title

Quote length and PR title has been fixed, as requested @Miodec

2024-05-15 13:24 UTC, Miodec requested changes
Please update pr title aswell.

2024-05-15 13:24 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "He who has a 'why' to live for can bear almost any 'how'.",
Use double quotes (dont forget to escape `\"`) instead of singles.

2024-05-16 03:52 UTC, triach-rold commented on frontend/static/quotes/english.json
> +      "text": "He who has a 'why' to live for can bear almost any 'how'.",
Done.

2024-05-18 19:47 UTC, triach-rold commented on frontend/static/quotes/english.json
> +      "text": "He who has a 'why' to live for can bear almost any 'how'.",
@Miodec I believe the requested changes have been made ?

2024-05-20 10:27 UTC, Miodec commented
Please resolve conflicts

2024-05-30 05:36 UTC, Warrobot10 commented
Please change the pr title to something like impr(quotes): added a new quote(triach-rold)
We do this so we can easily understand what area the change focuses on, and then allows the release system to list the changes in the release notes.

2024-06-03 10:45 UTC, closed without merging