impr(quotes): created and added quote to english.json (ElijahRosal)
monkeytypegame/monkeytype pull request #5380
Opened 2024-05-09 22:18 UTC by ElijahRosal

### Description

Added a quote to english.json
### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #

2024-05-09 22:21 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9024264714

2024-05-13 09:43 UTC, Miodec requested changes

2024-05-13 09:43 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "length": 160,
`Spinning our own versions of the past that you could nеver know cause I know.` i feel like there is a comma missing here somewhere

2024-05-13 17:41 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9067363908

2024-05-15 13:31 UTC, Miodec approved these changes

2024-05-15 13:31 UTC, merged

2024-05-15 13:31 UTC, Miodec commented
Thanks