test: add endpoint to create test user/data (fehmer)
monkeytypegame/monkeytype pull request #5396
Opened 2024-05-15 13:26 UTC by fehmer

2024-05-16 10:25 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9110631928

2024-05-16 10:28 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9110677045

2024-06-03 10:44 UTC, Miodec requested changes

2024-06-03 10:44 UTC, Miodec commented on backend/src/api/routes/index.ts
> +  "/dev": dev,
If you do it this way, there is a possibility this gets active in production.

Use the `if (isDevEnvironment())` check below and add it there, then remove it from the configuration.

2024-06-03 16:57 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9354195639

2024-06-17 13:21 UTC, Miodec approved these changes
Thanks

2024-06-17 13:21 UTC, merged