impr: Added two-step highlighting for accented characters that require the use of dead keys (theiereman)
monkeytypegame/monkeytype pull request #5480
Opened 2024-06-09 18:57 UTC by theiereman

### Description

Some accented characters require the use of dead keys ("^" ; "¨" on AZERTY keyboards for example) and I noticed the layout wasn't highlighting the dead key when their use was necessary.

- added highlight of the required dead key press for the characters having "^" ; "¨" and "~" accents
- if accented character is already present on the layout it will highlight that one and not the dead key
- added two-step highlight once a dead key was pressed to highlight the next character required to finish the accented character (exemple : "ê" will highlight "^" key and once pressed will highlight "e" key)
- if no key was mapped on layout to create the required accent, behavior will be the same as before = no highlight

Exemple for accented character already present on layout (BEPO) : 
![firefox_5xenPxc9Cv](https://github.com/monkeytypegame/monkeytype/assets/141121240/7bbaafb4-e06f-4f3a-9b99-4dbdd6fb170f)

Exemple for 2-steps accented character highlight (AZERTY) : 
![firefox_uiB7P97Ua0](https://github.com/monkeytypegame/monkeytype/assets/141121240/57cafe7e-4caf-415a-b8da-475807f4c6db)

Known issue : 
- I found no way to differentiate the dead key presses while still having a layout agnostic behavior so any dead key press will trigger the "2-step highlight" even if the required dead key character is wrong (exemple for "ê" : if you press "~", "e" will still get highlighted even if the finished character will generate an error

2024-06-09 18:59 UTC, theiereman commented on frontend/src/ts/elements/keymap.ts
> +
didn't really know where to put this

2024-06-09 18:59 UTC, theiereman commented on frontend/static/layouts/_list.json
> +    "keymapShowTopRow": true,
top row is required to show accented characters like "é" and "à"

2024-06-09 19:00 UTC, theiereman commented on frontend/src/ts/utils/strings.ts
> +  };
same for that map, didn't really know where to put it

2024-06-10 14:14 UTC, Miodec requested changes

2024-06-10 14:14 UTC, Miodec commented on frontend/static/layouts/_list.json
> +      "row1": ["`", "&1", "é2~", "\"3", "'4", "(5", "-6", "è7", "_8", "ç9", "à0", ")°", "=+"],
Whats the purpose of this?

2024-06-10 14:14 UTC, Miodec commented on frontend/src/ts/utils/strings.ts
> +  };
We already have `lazy-mode.ts` which includes a big list of accented and de-accented characters.

2024-06-10 14:14 UTC, Miodec commented on frontend/src/ts/elements/keymap.ts
> +    console.log("highlighting", highlightKey);
Im not sure i like this approach, why not modify the function call instead of doing this hacky change?

2024-06-10 14:14 UTC, Miodec commented on frontend/src/ts/elements/keymap.ts
> +
This should probably be defined per language, somewhere in the constants directory.

2024-06-10 14:43 UTC, theiereman commented on frontend/static/layouts/_list.json
> +      "row1": ["`", "&1", "é2~", "\"3", "'4", "(5", "-6", "è7", "_8", "ç9", "à0", ")°", "=+"],
tilde is on Digit2 for AZERTY keyboards

![image](https://github.com/monkeytypegame/monkeytype/assets/141121240/dbd3d14a-fd1a-4018-b439-eec11ca25ee4)

2024-06-10 14:50 UTC, Miodec commented on frontend/static/layouts/_list.json
> +      "row1": ["`", "&1", "é2~", "\"3", "'4", "(5", "-6", "è7", "_8", "ç9", "à0", ")°", "=+"],
Im assuming the blue is the alt layer? Can you add the rest of the characters?

2024-06-10 15:57 UTC, theiereman commented on frontend/src/ts/elements/keymap.ts
> +    console.log("highlighting", highlightKey);
I agree that it is a hacky change but I'm not sure I understand what you mean, sorry. I thought this was the best location to implement that behavior because it was central

2024-06-10 16:18 UTC, theiereman commented on frontend/static/layouts/_list.json
> +      "row1": ["`", "&1", "é2~", "\"3#", "'4{", "(5[", "-6|", "è7`", "_8\\", "ç9", "à0@", ")°]", "=+}"],
I didn't add the "^" on Digit9 because would conflict with "^¨" on `row2` and to be fair, no one uses that to write French. The only use I can imagine is math power symbol.

Exemple for conflict if added on Digit9 :
![image](https://github.com/monkeytypegame/monkeytype/assets/141121240/76a9c4d2-bbd3-4293-81ec-cc2d5382da29)

2024-06-16 21:39 UTC, Miodec commented on frontend/src/ts/elements/keymap.ts
> +    console.log("highlighting", highlightKey);
I mean instead of calling `highlightKey` with `á`, call it with `´` and then `a`.

2024-06-16 21:41 UTC, Miodec commented
Initial testing:

 - the highlighting behavior happens even when keymap mode is NOT set to `next`
 - if the compose character is the last one, keymap suggest space instead of `a`
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/d366b157-e178-4c61-b4dd-427ed63bed4d)

2024-06-17 17:13 UTC, theiereman commented
@Miodec I can't even reproduce the bugs of your initial testing, it's so weird

Tbh I think that improvement is not really worth the effort and what I did feels overall really clunky
The fact that every special character is not shown on the layout (so can't really be highlighted) and that "dead key detection" is global to every dead key, makes it a very minor (if any) improvement. 

I'm ok with you closing that PR if you're ok with it.

PS : maybe you should just keep the modification I did on AZERTY layout

2024-06-24 11:44 UTC, Miodec commented
> @Miodec I can't even reproduce the bugs of your initial testing, it's so weird
> 
> Tbh I think that improvement is not really worth the effort and what I did feels overall really clunky The fact that every special character is not shown on the layout (so can't really be highlighted) and that "dead key detection" is global to every dead key, makes it a very minor (if any) improvement.
> 
> I'm ok with you closing that PR if you're ok with it.
> 
> PS : maybe you should just keep the modification I did on AZERTY layout

Yeah, keep the layout modifications and revert everything else (or open a new pr)

2024-06-25 08:23 UTC, Miodec approved these changes
Thanks

2024-06-25 08:24 UTC, merged