style(fonts): Add mononoki font (@guillermodotn).
monkeytypegame/monkeytype pull request #5577
Opened 2024-07-07 09:32 UTC by guillermodotn

### Description

This PR adds the **Mononoki** font as proposed on discussion #5576, to the list of built-in fonts that Monkeytype ships with.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

2024-07-07 11:06 UTC, fehmer commented on frontend/src/styles/fonts.scss
> +  src: url("/webfonts/mononoki-Regular.ttf") format("truetype"),
do we need both? Shouldn't `otf` be the better choice?

2024-07-07 12:56 UTC, guillermodotn commented
I will suggest the following two modifications `monkeytype/frontend/src/styles/fonts.scss`:

1. A comment stating the `src` preference, like:

```scss
// In the case that both .otf and .ttf font sources are available,
// we choose the .otf format over the .ttf format due to its advanced 
// typographic features and better support for modern typesetting.
```

2. Delete the `.ttf` src for the font `Boom` if it is not needed, to simplify the file. 
Refer to [fonts.scss#L182](https://github.com/monkeytypegame/monkeytype/blob/aac44aead339cfd69c36e5a75a2e3945a44dd3d5/frontend/src/styles/fonts.scss#L182)

2024-07-07 13:28 UTC, monkeytypegeorge commented
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/9827688646

2024-07-07 14:36 UTC, guillermodotn commented on frontend/src/styles/fonts.scss
> +  src: url("/webfonts/mononoki-Regular.ttf") format("truetype"),
I agree with you, let's stick to `.otf` src.

2024-07-09 12:46 UTC, Miodec requested changes

2024-07-09 12:46 UTC, Miodec commented on frontend/static/about/contributors.json
No need for this, contributors are generatec automatically and ordered by the number of contributions. Please revert.

2024-07-09 12:46 UTC, Miodec commented on frontend/static/webfonts/mononoki-Regular.otf
Rename to `Mononoki-Regular.otf`

2024-07-09 15:47 UTC, Miodec commented
Also, please switch to `woff` if possible (we are changing everything to `woff` in #5582)

2024-07-09 15:59 UTC, closed without merging

2024-07-09 15:59 UTC, Miodec commented
Nevermind sorry, @fehmer already added Mononoki in his PR!

2024-07-09 16:00 UTC, fehmer commented
hi @guillermodotn . I'm sorry. I was updating the fonts to use woff2 and there was a misunderstanding with mio. I thought your PR is going to be merged first.