test: add mc/dc test to function updateAltGrState (@marcosatc147)
monkeytypegame/monkeytype pull request #5656
Opened 2024-07-26 02:09 UTC by Marcosatc147

added mc/dc based test to function updateAltGrState
fixed errors highlighted in previous pr

2024-07-26 10:46 UTC, Miodec commented on frontend/src/ts/test/layout-emulator.ts
Im thinking instead of exporting a function to directly alter the state, which could lead to dev error, maybe we should emulate keyup events in the tests instead?

2024-07-26 10:46 UTC, Miodec commented
Btw, there is no need to open a new pull request, you can just push your changes to your master branch and they will show up here.

2024-07-26 14:49 UTC, Miodec commented
Your last commit - it seems like you merged your own master instead of the upstream master, which means you are reverting one of the changes on master. You will need to revert your last commit.

2024-07-27 00:21 UTC, Marcosatc147 commented
now, is it right?

2024-07-27 15:09 UTC, Miodec commented
Your pr includes some unwanted changes with the packages. Please revert them.

2024-07-28 09:04 UTC, Miodec requested changes
Well done, PR is almost good to go. Just one more thing from my very first review.

2024-07-28 09:04 UTC, Miodec commented on frontend/src/ts/test/layout-emulator.ts
> +
Since you are emulating a keyup event and no longer using this function in the tests, this addition is not needed. (you probably added it back in by accident when reverting the package.json changes). Please remove.

2024-07-28 18:27 UTC, Miodec requested changes

2024-07-28 18:27 UTC, Miodec commented on frontend/src/ts/test/layout-emulator.ts
> +export { isAltGrPressed };
Sorry, one more thing i missed - exported variables can be modified. Instead of exporting this object, please export a getter function instead.

2024-07-28 19:02 UTC, merged

2024-07-28 19:02 UTC, Miodec commented
Thanks

2024-07-28 19:48 UTC, Marcosatc147 commented
Thank you!