impr(settings): added resize option to keymap (from 0x to 3.5x)
monkeytypegame/monkeytype pull request #5659
Opened 2024-07-27 00:42 UTC by butterflycup

The keymap cannot be resized, it can sometimes feel pretty small, especially when learning a new layout. This adds a setting called "Keymap Size" in which you can change the scale of the keymap (1 being default, I put 3.5 as maximum as anything higher wouldn't fit anyways)

2024-07-28 09:07 UTC, Miodec requested changes

2024-07-28 09:07 UTC, Miodec commented on frontend/.vscode/settings.json
Remove this file please.

2024-07-28 09:07 UTC, Miodec commented on frontend/src/html/pages/settings.html
> +    <div class="text">Change the scale of the keymap.</div>
scale > size

2024-07-28 09:07 UTC, Miodec commented on frontend/src/ts/config.ts
> +  }
This allows the size to be 0, which could be confusing if the keymap is enabled but still invisible. I would limit this to 0.5

2024-07-28 09:07 UTC, Miodec commented on frontend/src/html/pages/settings.html
> +        <button class="save no-auto-handle">
Update min property to 0.5 and add max with 3.5

2024-07-28 12:41 UTC, Miodec commented
By scale > size i meant to change the text "scale" to "size", not changing everything to scale :D Sorry for the ambigous comment.

2024-07-28 12:42 UTC, Miodec commented
![image](https://github.com/user-attachments/assets/ac2c3e33-913c-486c-928c-a8e979f8e89c)

2024-07-28 12:55 UTC, butterflycup commented
My bad, though in the end I guess scale makes more sense than size anyway, which one do you prefer ?

2024-07-28 12:56 UTC, Miodec commented
Other settings use size - lets stick with that.

2024-07-28 18:44 UTC, Miodec requested changes
Please hide the settings group if keymap is not enabled (just like the other settings which alter the keymap)

Also, what do you think about changing this to a slider (just like the custom background filter settings?)

![image](https://github.com/user-attachments/assets/e2e48d71-89d5-4065-89f2-4dc10db5128d)

![image](https://github.com/user-attachments/assets/e7bf5f2a-12cc-41b5-9c3b-1445a17b84cf)

2024-07-28 19:15 UTC, butterflycup commented
Keymap setting groups now hides, I prefer number input instead of slider. I'd go for slider if the changes were visible in real time (like for the custom background), but since the keymap is not visible in the settings page (and there's no slider in command line) I prefer number input, though I think both works. Maybe it'd be good to ask other people's opinion?

2024-07-29 09:23 UTC, Miodec commented
> Keymap setting groups now hides, I prefer number input instead of slider. I'd go for slider if the changes were visible in real time (like for the custom background), but since the keymap is not visible in the settings page (and there's no slider in command line) I prefer number input, though I think both works. Maybe it'd be good to ask other people's opinion?

Well, there is no slider for any of the settings in the commandline.

The slider makes more sense in this case because the value of this setting is limited between two values, and the range is quite small. @fehmer also liked the slider a bit more.

2024-07-29 10:21 UTC, butterflycup commented
I am way out of my comfort zone and I'm guessing this is why there is conflict with my fork (I couldn't figure out why), I'd appreciate the help a lot

2024-07-29 11:00 UTC, fehmer commented
> I am way out of my comfort zone and I'm guessing this is why there is conflict with my fork (I couldn't figure out why), I'd appreciate the help a lot

hi @butterflycup , i'm done with syncing your branch with monkeytype master and adapted to the new approach. You can take it from here.

2024-07-29 11:37 UTC, Miodec commented
> I think waiting for a slider implementation would unnecessarily postpone this feature of keymap resizing.

Converting to a slider would take like half an hour max.

2024-07-29 11:50 UTC, Miodec commented
Ill go ahead and convert to a slider

2024-07-29 11:59 UTC, butterflycup commented
Thank you all, I did the best I could, and while Miodec is right that it would take "half an hour max", I have to admit I am a noob and it wouldn't be as easy for me. Thank you for taking over

2024-07-29 12:18 UTC, Miodec commented
> Thank you all, I did the best I could, and while Miodec is right that it would take "half an hour max", I have to admit I am a noob and it wouldn't be as easy for me. Thank you for taking over

No worries, it was a big ask to be fair.

2024-07-29 12:39 UTC, merged