fix: fix ipv6 compression (rizwanmustafa)
monkeytypegame/monkeytype pull request #5682
Opened 2024-07-30 04:00 UTC by rizwanmustafa

### Description

Fixes the problem with compressing IPv6 addresses.

Closes #5622

2024-07-30 04:42 UTC, rizwanmustafa commented
A sample run on NodeJS gives us the following:
![image](https://github.com/user-attachments/assets/041914bb-3baf-42e5-bcde-2f48cb459d55)

2024-07-30 07:33 UTC, fehmer commented
hi @rizwanmustafa , could you add your examples as unit tests?

2024-07-30 08:07 UTC, fehmer submitted a review, later dismissed

2024-07-30 10:35 UTC, Miodec requested changes

2024-07-30 10:35 UTC, Miodec commented on frontend/src/ts/test/funbox/funbox.ts
> +      // console.log("Compressed IP: " + w);
Remove logs

2024-07-30 10:35 UTC, Miodec commented on frontend/__tests__/utils/ip-addresses.spec.ts
> +});
Should we have some sort of v4 tests? Would there be anything to test?

2024-07-30 11:03 UTC, rizwanmustafa commented on frontend/__tests__/utils/ip-addresses.spec.ts
> +});
I believe there could be tests for IPv4. Maybe a check that the numbers don't exceed 255. Example `256.255.255.255` is an invalid Ipv4 address

2024-07-30 11:03 UTC, rizwanmustafa commented on frontend/src/ts/test/funbox/funbox.ts
> +      // console.log("Compressed IP: " + w);
ok

2024-07-30 11:48 UTC, rizwanmustafa commented on frontend/__tests__/utils/ip-addresses.spec.ts
> +});
Done

2024-07-31 10:00 UTC, Miodec approved these changes
https://media1.tenor.com/m/cOsiTargIp8AAAAC/hes-back.gif

2024-07-31 10:00 UTC, merged