feat(settings): allow partial presets (@amarnathsama)
monkeytypegame/monkeytype pull request #5813
Opened 2024-08-21 20:11 UTC by amarnathsama

### Description
Allows creation of create partial presets.

Key Points-
1) For active setting groups, all settings including defaults are saved and set.
2) For inactive groups, settings are unchanged when preset is applied.

### Checks

- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #4532

2024-08-21 21:18 UTC, fehmer commented on frontend/src/ts/config.ts
> +export async function selectiveApply(
could you add tests for this?

2024-08-21 21:22 UTC, fehmer commented on packages/contracts/src/schemas/presets.ts
> +export const presetSettingGroupSchema = z.enum([
please start schemas with uppercase letter

2024-08-21 21:23 UTC, fehmer commented on packages/contracts/src/schemas/presets.ts
> +  "hide elements",
i'd use `hideElements`

2024-08-21 21:25 UTC, fehmer commented on packages/contracts/src/schemas/presets.ts
> +    settingGroups: activeSettingGroupsSchema,
i guess this should be optional. if all groups are selected have it empty to keep it the same as current "full" presets.

2024-08-21 21:27 UTC, fehmer commented on packages/contracts/src/schemas/presets.ts
> +  .superRefine((settingList, ctx) => {
please add a test case in `controllers/preset.spec.ts`

2024-08-21 21:31 UTC, amarnathsama commented on packages/contracts/src/schemas/presets.ts
> +    settingGroups: activeSettingGroupsSchema,
keeping it undefined makes a preset indistinguishable from a legacy preset, which we need to be able to determine to migrate legacy values, how about i keep the list empty for full?

2024-08-21 21:52 UTC, fehmer commented on frontend/src/ts/modals/edit-preset.ts
> +      return presetSettingGroupSchema.Enum.theme;
you can just return the value as string, e.g. `"theme"` typescript will check this is a valid enum value

2024-08-21 21:54 UTC, fehmer commented on backend/__tests__/api/controllers/preset.spec.ts
i'm not sure about this changes. I guess we will still need to support "legacy"/full presets. You can edit existing presets on the settings page and apply the current settings to them.

In addition we should avoid breaking changes if possible so we don't cause issues in old clients.

2024-08-23 21:03 UTC, amarnathsama commented on packages/contracts/src/schemas/presets.ts
> +export const presetSettingGroupSchema = z.enum([
Updated

2024-08-23 21:03 UTC, amarnathsama commented on packages/contracts/src/schemas/presets.ts
> +  "hide elements",
Updated

2024-08-23 21:03 UTC, amarnathsama commented on packages/contracts/src/schemas/presets.ts
> +    settingGroups: activeSettingGroupsSchema,
Updated

2024-08-23 21:04 UTC, amarnathsama commented on frontend/src/ts/modals/edit-preset.ts
> +      return presetSettingGroupSchema.Enum.theme;
fixed

2024-08-23 21:04 UTC, amarnathsama commented on backend/__tests__/api/controllers/preset.spec.ts
fixed

2024-08-23 21:24 UTC, amarnathsama commented on packages/contracts/src/schemas/presets.ts
> +  .superRefine((settingList, ctx) => {
done

2024-08-24 11:56 UTC, amarnathsama commented on frontend/src/ts/config.ts
> +export async function selectiveApply(
done

2024-08-28 09:10 UTC, Miodec requested changes
One more thing i found - while editing a preset, the full/partial option should only show if you check "change preset to current settings"

2024-08-29 21:09 UTC, amarnathsama commented on frontend/src/ts/modals/edit-preset.ts
> +}
done

[commit link](https://github.com/monkeytypegame/monkeytype/pull/5813/commits/78e549e7f83ee8736cfd06cc21ed5f1a81567f4f)

please let me know if this is good.

2024-08-29 21:10 UTC, amarnathsama commented on frontend/src/ts/modals/edit-preset.ts
> +  }
done

2024-08-29 21:10 UTC, amarnathsama commented
> One more thing i found - while editing a preset, the full/partial option should only show if you check "change preset to current settings"

done

2024-09-08 19:53 UTC, fehmer commented on packages/contracts/src/schemas/presets.ts
> +export const EditPresetRequestSchema = PresetSchema.extend({
```ts
export const EditPresetRequestSchema = PresetSchema.partial({
  config:true
})```

2024-09-08 19:57 UTC, fehmer commented on backend/src/dal/preset.ts
> +export async function editPreset(
i'd implement it this way:
```ts
export async function editPreset(uid: string, preset: Preset): Promise<void> {
  const update: Partial<Omit<Preset, "_id">> = omit(preset, "_id");

  if (
    preset.config === undefined ||
    preset.config === null ||
    Object.keys(preset.config).length === 0
  ) {
    delete update.config;
  }

  await getPresetsCollection().updateOne(getPresetKeyFilter(uid, preset._id), {
    $set: update,
  });
}
```

2024-09-09 16:21 UTC, amarnathsama commented on backend/src/dal/preset.ts
> +export async function editPreset(
fixed

2024-09-09 19:34 UTC, Miodec submitted a review, later dismissed

2024-09-10 07:12 UTC, fehmer commented on backend/__tests__/dal/preset.spec.ts
> +      const second = (
Example:
```ts
 it("should edit when partial is edited to full", async () => {
      //GIVEN
      const uid = new ObjectId().toHexString();
      const preset = (
        await PresetDal.addPreset(uid, {
          name: "first",
          settingGroups: ["hideElements"],
          config: {
            showKeyTips: true,
          },
        })
      ).presetId;

      //WHEN
      await PresetDal.editPreset(uid, {
        _id: preset,
        name: "newName",
        config: { ads: "off" },
      });

      //THEN
      const read = await PresetDal.getPresets(uid);
      expect(read[0]).toEqual(
        expect.objectContaining({
          _id: new ObjectId(preset),
          uid: uid,
          name: "newName",
          config: { ads: "off" },
          settingGroups: null,
        })
      );
    });
```

2024-09-10 13:25 UTC, amarnathsama commented on backend/__tests__/dal/preset.spec.ts
> +      const second = (
fixed

2024-09-12 19:42 UTC, merged

2024-09-12 19:42 UTC, Miodec commented
Thanks