fix(presets): Bug fix for auto-switch theme checkbox values (@amarnathsama)
monkeytypegame/monkeytype pull request #5826
Opened 2024-08-26 21:29 UTC by amarnathsama

### Description

Fixes bug where applying a preset wouldn't update the auto switch theme light and dark theme checkbox values (pictured below).
![image](https://github.com/user-attachments/assets/3f77fab4-6752-452f-b6b7-4c26a8b83fbc)

### Checks

- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

2024-08-27 11:16 UTC, Miodec requested changes

2024-08-27 11:16 UTC, Miodec commented on frontend/src/ts/config.ts
I would prefer to not add more DOM modifying code in the config module. Please use the config event instead and add this code in settings.ts

2024-08-28 05:54 UTC, amarnathsama commented on frontend/src/ts/config.ts
I have made the changes, please let me know if they are good or not.

2024-08-28 08:40 UTC, Miodec requested changes

2024-08-28 08:40 UTC, Miodec commented on frontend/src/ts/pages/settings.ts
> +ConfigEvent.subscribe((eventKey, eventValue) => {
Please move this inside the subscribe function thats just above.

2024-08-28 16:01 UTC, amarnathsama commented on frontend/src/ts/pages/settings.ts
> +ConfigEvent.subscribe((eventKey, eventValue) => {
done

2024-08-29 10:39 UTC, Miodec approved these changes
Thanks

2024-08-29 10:40 UTC, merged