chore(PR labeler): fix workflow having read access only, when triggered from forks (@NadAlaba)
monkeytypegame/monkeytype pull request #5842
Opened 2024-09-01 19:07 UTC by NadAlaba

### Description

- Previous automatic PR labeler doesn't work when triggered from forks because workflows triggered from forks by the events `pull_request` and `pull_request_review` have read access only, and can't write to PRs (change labels).

- This is an attempt to solve this issue by splitting the workflow in 2:
One with read access only, that gets triggered by those events, and when completed another workflow would run with write access that would perform the change.

- I added everything I could think of to the list of conditions to update the labels (because removing conditions later is easier than going back to the docs and adding more conditions). You may need to go over this list and remove what you deem unnecessary.

2024-09-02 06:22 UTC, fehmer requested changes

2024-09-02 06:22 UTC, fehmer commented on .github/workflows/update-labels.yml
> +          RESULT_JSON: ${{ format('{{"waiting_for_review"{0} {1}, "waiting_for_update"{0} {2}, "pr_url"{0} "{3}"}}', ':', env.REVIEW, env.UPDATE, env.PR_URL) }}
let's only include the pr number here

2024-09-02 06:22 UTC, fehmer commented on .github/workflows/write-labels.yml
> +        run: gh pr edit ${{ env.PR_URL }} --add-label "waiting for review"
I'm not 100% sure this can be used for code injection. To be safe lets use the github actions you used previously and pass in the pr number only.

2024-09-02 06:22 UTC, fehmer commented on .github/workflows/write-labels.yml
> +  issues: write
why do we need write access on issues?

2024-09-02 06:22 UTC, fehmer commented on .github/workflows/update-labels.yml
> +          path: ./result.json
can we use a better name? e.g. `write-labels.json`

2024-09-02 17:18 UTC, NadAlaba commented on .github/workflows/write-labels.yml
> +  issues: write
the labeler removes the 'waiting for update' label on comments by the author on issues too.
So you can add the label manually and it'll get removed automatically.

2024-09-02 17:18 UTC, NadAlaba commented on .github/workflows/update-labels.yml
> +          path: ./result.json
sure

2024-09-02 17:20 UTC, NadAlaba commented on .github/workflows/write-labels.yml
> +        run: gh pr edit ${{ env.PR_URL }} --add-label "waiting for review"
I made the change although I don't fully get the risk

2024-09-03 14:07 UTC, fehmer approved these changes
lgtm

2024-09-05 11:44 UTC, merged

2024-09-05 11:44 UTC, Miodec commented
Thanks