impr(language): add common javascript words, symbols and functions (@bdsqqq)
monkeytypegame/monkeytype pull request #5869
Opened 2024-09-10 21:52 UTC by bdsqqq

### Description

Adds commonly used symbols:
- quotes,
- ticks
- double quotes
- square brackets
- curly brackets

Adds commonly used functions and patterns (eg: spread operations, arrows used in arrow functions)

### Checks

- [x] Adding quotes?
  - [x] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [x] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

2024-09-11 08:53 UTC, fehmer commented on frontend/static/languages/code_javascript.json
> +    "className",
not sure about adding React or other framework code in the javascript language file. For e.g. backend javascript developers this is pretty useless. We could add code_react as a language.

2024-09-11 09:27 UTC, Miodec requested changes

2024-09-11 09:27 UTC, Miodec commented on frontend/static/languages/code_javascript.json
> +    "className",
I agree

2024-09-11 11:54 UTC, bdsqqq commented on frontend/static/languages/code_javascript.json
> +    "className",
Makes a lot of sense, idea of adding these came to mind since jQuery is in the list of words. Will remove the library related ones and open a new PR with react as a language. ty!

2024-09-11 12:23 UTC, bdsqqq commented on frontend/static/languages/code_javascript.json
> +    "className",
also, there is a quote in the js language that is just a react example. Bringing it up in case you think this could be made into an issue and then removed

https://github.com/monkeytypegame/monkeytype/blob/b315836deefc51fcbeaab15b105e486fdc6c5971/frontend/static/quotes/code_javascript.json#L30

2024-09-11 12:37 UTC, bdsqqq commented on frontend/static/languages/code_javascript.json
> +    "className",
moved frontend specific things to: https://github.com/monkeytypegame/monkeytype/pull/5873/files

2024-09-12 18:52 UTC, Miodec approved these changes
Thanks

2024-09-12 18:59 UTC, merged

2024-09-22 02:14 UTC, dcousens commented on frontend/static/languages/code_javascript.json
> +    "className",
Arguably the Apollo keywords `readQuery`, `readFragment` et al don't have a place either