refactor: split updateWordsHeight() and move some style changes to .scss files (@NadAlaba)
monkeytypegame/monkeytype pull request #5920
Opened 2024-09-26 15:56 UTC by NadAlaba

### Description

- split the tasks of `updateWordsHeight()` into `updateWordsWrapperHeight()` and `updateWordsMargin()` and the remaining tasks are done in `test.scss` (`width` and `overflow`) since they depend on the `.tape` class only.

2024-10-07 15:58 UTC, Miodec requested changes
Biggest issue so far is that this PR makes zen mode very jumpy:


https://github.com/user-attachments/assets/252d332d-1dcc-47ff-a5d4-63b207743ea7

2024-10-07 15:58 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
>      void updateWordsInputPosition(true);
Instead of these, maybe we should just use `updateWordWrapperClassses`?

2024-10-07 15:58 UTC, Miodec commented on frontend/src/ts/test/test-ui.ts
> +    }, 125);
We should either remove this delay or reduce it to 0 because it creates a visual bug where the words remain offset to the right when switching tape mode off:

https://github.com/user-attachments/assets/2ff1d497-5740-40e7-9c09-2acce610cde0

2025-03-31 12:22 UTC, merged

2025-03-31 12:28 UTC, NadAlaba commented
> 7 month pr :X thanks and sorry

tbh most of the delay was mine, but it's good to see it done