Add Bengali Language
monkeytypegame/monkeytype pull request #5924
Opened 2024-09-28 05:43 UTC by SubhodeepRoy2

Added Bengali as a language using the English alphabet (transliteration). Although Bengali was already included, it was in the Bengali script. This contribution adds Bengali words written in the English alphabet.

2024-09-28 08:25 UTC, rammba commented
Does it make sense to put it in the same language group as already existing language? I think we have similar case for Serbian, where we use both cyrillic and latin versions.

2024-09-28 08:45 UTC, SubhodeepRoy2 commented
That can also be done. or it could be added as a separate language variant. Both works, what's your suggestion?

2024-09-28 09:13 UTC, rammba commented
I would say it's better to group them, since they are related. I see that also sanskrit language is in the [same group](https://github.com/monkeytypegame/monkeytype/blob/fa58e090db77fb7dfb98d3db6315bf94f4e8e7b9/frontend/static/languages/_groups.json#L421C20-L421C28) as sanskrit_roman which is similar case as yours, right?

2024-09-28 11:20 UTC, SubhodeepRoy2 commented
hey @rammba can you help me with the errors that I'm getting here?
<img width="341" alt="image" src="https://github.com/user-attachments/assets/f02acd8b-a6f4-4d45-b5cc-3e5ee62898e8">

2024-09-28 12:21 UTC, rammba commented
I think you should rename title of this PR to something like: `feat(bengali): add Bengali language (@SubhodeepRoy2)`.

2024-10-07 10:27 UTC, Miodec requested changes

2024-10-07 10:27 UTC, Miodec commented on frontend/static/languages/_groups.json
>  ]
This file (and the _list file) is meant to be ordered roughly by popularity. Please update the position of bengali.

2024-10-31 20:35 UTC, closed without merging