impr(quotes): add French quotes
monkeytypegame/monkeytype pull request #5938
Opened 2024-10-03 18:13 UTC by gambergeurr

# Add french quotes 1123 to 1125

## English traduction

- ### 1123
It was a square room, barely two toises on a side, with dirty grey cement walls. On three sides, the walls were pierced by a tall, narrow frosted-glass window, doubly protected by a wire mesh and black iron bars, making three windows in all, which gave the room a stern, perpetually on-guard look. Against the only blind wall was a bed, also sturdy and made of iron, with its head towards the door, but judging from the white sheets folded and perfectly aligned on it, nobody had slept on it yet.
- ### 1124
Laugh if you like. It's awful, incurable. I'm afraid of the walls, the furniture, the familiar objects that come alive for me with a kind of animal life. Above all, I'm afraid of the horrible confusion of my thoughts, of my reason that escapes me, blurred and scattered by a mysterious and invisible anguish.
- ### 1125
Bish it's disgusting if he doesn't listen he'll call our blows low. Thinking is a job when I make R bish I don't take it easy. I want a B, I don't take it.

2024-10-05 20:47 UTC, ambr0sial commented
🇲🆖

2024-10-05 20:48 UTC, Lenochxd commented
MNG 🔥🔥🔥

2024-10-07 11:36 UTC, Miodec requested changes

2024-10-07 11:36 UTC, Miodec commented on frontend/static/quotes/french.json
> +      "length": 155,
Please remove

2024-10-24 05:06 UTC, closed without merging