impr(quotes): add another star trek quote (@266-750Balloons)
monkeytypegame/monkeytype pull request #5946
Opened 2024-10-05 08:33 UTC by 266-750Balloons

This pull request adds the following quote from *Star Trek: Voyager*, a series which Monkeytype currently lacks:
> You are one of my most valued officers and you are my friend. It is vital that you understand me here. I need you, but I also need to know that I can count on you. You are my counsel, the one I turn to when I need my moral compass checked. We have forged this relationship for years and I depend on it. I realise you made a sacrifice for me, but it's not one I would have allowed you to make. You can use logic to justify almost anything. That's it's power, and it's flaw. From now on, bring your logic to me. Don't act on it behind my back.
- Captain Kathryn Janeway, Star Trek: Voyager | 541 characters

2024-10-07 11:14 UTC, Miodec requested changes

2024-10-07 11:14 UTC, Miodec commented on frontend/static/quotes/english.json
> +      "text": "You are one of my most valued officers and you are my friend. It is vital that you understand me here. I need you, but I also need to know that I can count on you. You are my counsel,
Please use US spelling (realise > realize).

2024-10-08 03:51 UTC, 266-750Balloons commented on frontend/static/quotes/english.json
> +      "text": "You are one of my most valued officers and you are my friend. It is vital that you understand me here. I need you, but I also need to know that I can count on you. You are my counsel,
Alright. Done.

2024-10-08 19:27 UTC, merged

2024-10-08 19:27 UTC, Miodec commented
Thanks