Add kenshin layout to _list.json
monkeytypegame/monkeytype pull request #5984
Opened 2024-10-25 06:06 UTC by inscapist

### Description

Adds kenshin layout featuring same hand h/j/k/l and  somewhat heavier pinky use

```
; u o g '  j b m l k
e i a d y  f n s r t
/ . x c q  p h w z v
```

- [cyanophage playground](https://cyanophage.github.io/playground.html?lan=english&layout=%3Buog%27jbmlk-eiadyfnsrt%2C%2F.xcqphwzv%5C%5E&mode=ansi)

![1729836329](https://github.com/user-attachments/assets/dfdb8f0a-e32b-4cac-ac0b-ed828ea19c61)

2024-10-28 09:04 UTC, Miodec requested changes

2024-10-28 09:04 UTC, Miodec commented on frontend/static/layouts/_list.json
> +  "kenshin 剣心": {
Please keep the layout name to latin characters.

2024-10-28 11:27 UTC, inscapist commented on frontend/static/layouts/_list.json
> +  "kenshin 剣心": {
removed!

2024-11-03 14:47 UTC, closed without merging

2024-11-03 14:47 UTC, inscapist commented
noticed some issue with the k letter position. Closed until its fixed!