feat: Added Fortran lang (@slammon)
monkeytypegame/monkeytype pull request #6009
Opened 2024-11-05 22:55 UTC by slammon

### Description

Added Fortran lang.

### Checks

- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `language.json`?
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

2024-11-05 23:28 UTC, someStranger8 commented
lgtm

2024-11-06 11:22 UTC, Miodec requested changes

2024-11-06 11:22 UTC, Miodec commented on frontend/static/languages/code_fortran.json
> +  "name": "Fortran",
This property should be the same as the filename.

2024-11-06 12:57 UTC, slammon commented on frontend/static/languages/code_fortran.json
> +  "name": "Fortran",
mb gang

2024-11-07 11:37 UTC, merged