add tibetan language
monkeytypegame/monkeytype pull request #6032
Opened 2024-11-11 16:57 UTC by lobnor2

### Description

add tibetan.json and tibetan_1k.json in the frontend/static/languages
update _groups.json and _list.json

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [ ] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #

2024-11-14 20:44 UTC, Miodec requested changes

2024-11-15 03:28 UTC, lobnor2 commented on frontend/static/languages/_groups.json
>      "name": "french",
i have arranged language by popularity. 
Have a look

2024-11-18 23:50 UTC, Miodec commented
Hey, you've got loads of duplicate words in the files. Please remove them.

2024-11-19 04:17 UTC, lobnor2 commented
> Hey, you've got loads of duplicate words in the files. Please remove them (the failing logs will say which ones are duplicates).

I have removed duplicate words.

2024-11-21 11:03 UTC, Miodec requested changes

2024-11-21 11:03 UTC, Miodec commented on frontend/static/languages/tibetan_1k.json
> +  "name": "tibetan",
This should be `tibetan_1k`

2024-11-21 13:50 UTC, lobnor2 commented on frontend/static/languages/tibetan_1k.json
> +  "name": "tibetan",
i have changed that

2024-11-21 14:11 UTC, merged

2024-11-21 14:11 UTC, Miodec commented
Thanks