feat(lang): add punjabi language (@SajanGhuman)
monkeytypegame/monkeytype pull request #6059
Opened 2024-11-19 15:14 UTC by SajanGhuman

### Description
This PR adds Punjabi  language to the list of languages

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #

2024-11-21 11:09 UTC, Miodec requested changes

2024-11-21 11:09 UTC, Miodec commented on frontend/static/languages/_list.json
Please revert the change in this file, its modifying every line.

2024-11-21 15:23 UTC, SajanGhuman commented on frontend/static/languages/_list.json
My Code Formatter was at fault. Changes made accordingly.

2024-12-01 16:40 UTC, SajanGhuman commented on frontend/static/languages/_list.json
Hi, can you please merge this. Let me know, if any changes are needed.

2025-01-02 16:04 UTC, Miodec commented
Closing due to build failing and inactivity.

2025-01-02 16:04 UTC, closed without merging