impr: center mini stats when using tape mode
monkeytypegame/monkeytype pull request #6100
Opened 2024-12-08 09:19 UTC by notTamion

### Description
old:
![image](https://github.com/user-attachments/assets/db11fa1c-f993-4ad0-9fcd-a5419bbea2ea)

new:
![image](https://github.com/user-attachments/assets/5956e4fb-6328-488b-a655-8d94c632ac42)

2024-12-09 11:57 UTC, Miodec commented
This will overlap the test modes notice when focus mode is disabled.

2024-12-09 13:42 UTC, notTamion commented
focus mode? how do i enable that? i can't find it in the settings.

2024-12-09 13:44 UTC, Miodec commented
Focus mode just refers to the ui hiding itself when you start typing.

2024-12-09 13:45 UTC, notTamion commented
yeah i thought that might be it but i don't know what its actually called.

2024-12-23 14:58 UTC, Miodec requested changes
Instead of modifying the dom from the config file, please move this change into `test-ui.ts` - at the end of the file there is a `ConfigEvent` subscriber - make the css change there.

2025-01-06 10:33 UTC, Miodec approved these changes
Thanks

2025-01-06 10:33 UTC, merged