feat(language): added tamil_old (@VIZL-23)
monkeytypegame/monkeytype pull request #6141
Opened 2024-12-28 08:05 UTC by VIZL-23

### Description

Added the version of Old Tamil Language(similar to old English,these words were used in plays and poems) words to the group of Tamil

### Checks

- [x] Adding a language or a theme?
  - [x] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

2024-12-28 08:34 UTC, VIZL-23 commented
I am not sure why check-pretty is failing altho everything is formatted properly.

2024-12-28 10:19 UTC, fehmer requested changes

2024-12-28 10:19 UTC, fehmer commented on frontend/static/themes/_list.json
unrelated change? please revert

2024-12-28 10:19 UTC, fehmer commented on frontend/static/languages/tamil_old.json
running `npm run pretty-fix` fixes two errors in this file:

```diff
diff --git a/frontend/static/languages/tamil_old.json b/frontend/static/languages/tamil_old.json
index 552160396..f39485ce7 100644
--- a/frontend/static/languages/tamil_old.json
+++ b/frontend/static/languages/tamil_old.json
@@ -1,4 +1,4 @@
-{   
+{
   "name": "tamil_old",
   "noLazyMode": true,
   "bcp47": "ta",
@@ -464,6 +464,6 @@
     "வசம்",
     "வண்ணப்பூ",
     "வழிமுறைகள்",
-    "வளர்ச்சி" 
+    "வளர்ச்சி"
   ]
 }
```

2024-12-28 11:29 UTC, VIZL-23 commented on frontend/static/themes/_list.json
My bad, I removed an old theme that I had made, I guess by mistake I had also removed the one above it. Extremely sorry.

2024-12-28 11:50 UTC, VIZL-23 commented on frontend/static/languages/tamil_old.json
@fehmer Thanks a lot, it worked!!

2025-01-06 10:59 UTC, Miodec approved these changes
Thanks

2025-01-06 11:00 UTC, merged